MikeSchulze/gdUnit4

addons/gdUnit4/src/core/GdUnitTestSuiteBuilder.gd, addons/gdUnit4/src/core/_TestSuiteScanner.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/ScriptEditorControls.gd, project.godot
The creation of a test case was broken and ends up in an error dialog
Fixes:
- refactor editor interactions and extract it to a external class
- fix save open scripts
- save current edited script before build the test case
- save, close reopen the testsuite on test creation to avoid script code inconsitency
=> GD-7, GD-22: Fix create a testcase via context menu

addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/ScriptEditorControls.gd, addons/gdUnit4/src/ui/menu/GdUnitContextMenuItem.gd, addons/gdUnit4/src/ui/menu/ScriptEditorContextMenuHandler.gd, addons/gdUnit4/test/core/GdUnitTestSuiteBuilderTest.gd, addons/gdUnit4/test/core/TestSuiteScannerTest.gd, project.godot
- complete rebuild the script editor context menu createn and execution
- introduce a context menu handler to handle menu visualisation and execution
- cleanup GdUnitInspector
=> GD-24: Fixes the script editor context menu to show `Create Test`

addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/ui/EditorFileSystemControls.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandler.gd, project.godot
- move all context menu related stuff into new tools `EditorFileSystemControls`
- cleanup `GdUnitInspector`
- add testsuite icon to testsuite
=> GD-27: Cleanup `GdUnitInspector` and move filesystem dock code into `EditorFileSystemControls`

addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd
#Why
The OS.execute was changed in Godot4 and the flag `blocking` was removed where results in a blocking thread and the editor was blocked 
#What
Fixed by use the new provided function `create_process` to spwan a new thread and run the scene into
=> GD-30: Fix run tests in release mode

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/core/GdUnitTestSuiteBuilder.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/test/GdUnitTestResourceLoader.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/mono/GdUnit3MonoAPITest.gd, project.godot
A user can change the texteditor setting to use custom ident.
e.i. Tabs vs Spaces
Use the editor settings to format the test function to expected ident,
=> GD-32: Create test case use configured text ident settings

addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd
A spy on a function without return information was returning null.
The FunctionDescriptor was interpreting a not set return type as a void function.
If a function has no typed return information we now interpreting as a Variant return type
=> GD-33: Spy is returning `<Null>` for non return typed methods

addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitStringAssertImpl.gd, addons/gdUnit4/src/core/GdDiffTool.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitArrayAssertImpl_PoolByteArrayTest.gd, addons/gdUnit4/test/asserts/GdUnitDictionaryAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitResultAssertImplTest.gd, project.godot
The failure report of `assert_dict` was broken and shows a list of numbers
- fixed to see human readable failure message
- cleanup/format code
=> GD-39: Fix unreadable failure report for `assert_dict` and improve failure messages for `assert_array`

addons/gdUnit4/src/cmd/CmdCommand.gd, addons/gdUnit4/src/cmd/CmdCommandHandler.gd, addons/gdUnit4/test/cmd/CmdCommandHandlerTest.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/spy/GdUnitSpyTest.gd
- enable CmdCommandHandlerTest#test_execute_commands_with_cb_registered():
- Code formating on CmdCommand and CmdCommandHandler
- enable GdUnitSpyTest#test_spy_on_inner_class():
=> GD-12: Reenable tests where was temporary disabled

addons/gdUnit4/plugin.gd, addons/gdUnit4/src/GdUnitTestSuite.gd
The node inspector was loading very long and each search action takes around a minute
Unregister GdUnit classes where inherits form Godot.Node form the node inspector
The classes are still shown in the inspector but the inspector is usable without timeouts
=> GD-15: Remove GdUnit classes inherits form Godot.Node form the node inspector

addons/gdUnit4/src/update/GdUnitUpdateNotify.tscn
The activation was failing because of adding a transient dialog where is not allowed at this context
Changed to non transient dialog
=> GD-52: Fix failing activation of GdUnit extension

addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd
Loading of a test suite with an parameterized test and a huge parameter set was resulting in extrem long loading time
- Simplifyed the function descriptor parsing to speedup loading time.
- Fix GdScript parse error on Godot4 beta10
=> GD-62: Improve test suite parsing for large function descriptors

addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/ParameterizedTestCaseTest.gd
Using dictionary on a parameterized was end up into a runtime error.
Fix the script parser to work with dictionaries as test arguments
=> GD-63: Using a dictionary parameter in parameterized tests results into a runtime error

addons/gdUnit4/src/core/GdUnitExecutor.gd, addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/core/GdUnitRunnerConfig.gd, addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
By default, you can execute only one selected test or test suite. For parameterized tests, the inspector is populated with all parameterized tests when the test is executed. If a test fails, you have to re-run the entire test case, but it would be nice if you could select one of the parameterized test runs and re-run it as a single case.
Implemented to run a selected parameterized test case via the inspector context menu.
=> GD-60: Allow to run a single parameterized test from the inspector

addons/gdUnit4/src/core/GdUnitSettings.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
I wan't to not auto collapse all testsuites after success testrun on the inspector
Added a inspector ui option to control the collapse state of a testsuite ![image](https://user-images.githubusercontent.com/347037/209402912-4a7054df-3fcf-4d0e-a32e-65e6f34cb264.png)
=> GD-64: Added an option to control the collapse state for a testsuite node on the inspector

addons/gdUnit4/src/ui/GdUnitInspector.gd
The command 'Debug Test' was not working on MacOS
Add a path argument to run the GdUnitRunner scene. Seems to be a required argument under macOS
=> GD-77: Fix run `Debug Test` on  MacOS

addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/test/core/GdUnitToolsTest.gd
The test run was aborted when using a pure class type on auto_free
The Godot function `is_instance_valid(instance)` is not recognice a class type as invalid. I added a hack to check by using `ClassDB.class_get_property(instance, "new")`
=> GD-83: Fix auto_free on class type aborts the test run without any messages

addons/gdUnit4/src/core/report/GdUnitReport.gd
When execution test in runtime mode (none debug) the failure line is reported as -1 Godot do not get the stacktrace on runtime mode to extract this information
Instead of reporting -1 report <n/a> for not available.
=> GD-70: Don't report -1 as failure line number at runtime mode

addons/gdUnit4/src/ui/GdUnitConsole.gd
The gdunit console was reporting an runtime error because of invalid indentation handling
- Reworked the console message handling to avoid invalid `pop` calls on RichTextLabel
- Add missing font initalisation to render messages with a mono font
=> GD-72: Fix gdunit console wrong indent of failure reports

addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitExecutor.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/core/GdUnitExecutorTest.gd, addons/gdUnit4/test/monitor/GodotGdErrorMonitorTest.gd, project.godot
When running test without debug info script errors was ignored and results into success
- Fix the error monitor to parse godot.log for script errors
- Fix function await assert runtime errors
- Fix runtime error when test for `is_engine_type`
- rework on test timeout report generation
- Moved reg_ex helper func to 'GdUnitTools.to_regex'
- Removed invalid prefix 'timeout!' from tree inspector when a test has state error
=> GD-88: Fix script runtime error detection

addons/gdUnit4/src/ui/GdUnitConsole.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/GdUnitToolsDialog.gd, addons/gdUnit4/src/ui/parts/InspectorProgressBar.gd, addons/gdUnit4/src/update/GdUnitUpdate.gd, addons/gdUnit4/src/update/GdUnitUpdateNotify.gd, addons/gdUnit4/test/ui/templates/TestSuiteTemplateTest.gd
Since beta15/16 the direct access to the editor interface over a manuall created editor plugin is broken.
Reuse the already stored `GdUnitEditorPlugin` instance from the engine meta store instead
=> GD-96: Fixed usage of `EditorPlugin.new()`

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/src/ui/parts/InspectorTreePanel.tscn
The plugin was shown an error when activating the signal `item_double_clicked` not exists.
Removed the connection to signal item_double_clicked
=> HotFix `InspectorTreeMainPanel` using invalid signal

addons/gdUnit4/test/core/GdUnitExecutorTest.gd
The test was setting `REPORT_ASSERT_STRICT_NUMBER_TYPE_COMPARE` to false at the end. And also do not initial set to true.
- Fix it by move the set to true before test execution
- do reset to default at the end of the test
=> Fix flaky unit test GdUnitExecutorTest

addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/network/GdUnitTcpServer.gd, addons/gdUnit4/test/network/GdUnitTcpServerTest.gd
Run tests over the whole project was resuling in a JSON parse exception. The received packages can be partial data and needs to handled before parsing.
- Rework on `TcpConnection` and store first data packages in a temporary read buffer.
- Process the read buffer and extract only valid packages by using the delemiter
- Add test coverage for handling partial data packages
- using a signal collector to check the expected RPC data is emitted
- simplify and improve SignalCollector by better error handling
=> GD-99: Fix JSON parse exception occures on TCPServer when  many tests executed

addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/GdUnitExecutorTest.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/core/ParameterizedTestCaseTest.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/mocker/resources/ClassWithCustomFormattings.gd
Using Strings containing spaces or tabs was failing on parameterized tests. The valus was distorted.
- Fix the test argument parsing by do not clean up the function signature to pare the arguments
- Fix also failing GdUnitExecutor test based on changed gdunit settings during test run
cherry-picked from GdUnit3
=> GD-75: Fix test parameter parsing of parameterized tests with String arguments

addons/gdUnit4/src/core/GdUnitClassDoubler.gd, addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd, addons/gdUnit4/test/core/parse/GdFunctionDescriptorTest.gd
Spy on a function with return type `Variant` was wrong doubled and has return always nothing.
- Check the usage flag of the return descriptor and check for `PROPERTY_USAGE_NIL_IS_VARIANT` to determine it is a `Variant`
=> GD-78: Fix spy on function with return type `Varaiant`

addons/gdUnit4/src/core/GdUnitExecutor.gd, addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/core/GdUnitRunnerConfig.gd, addons/gdUnit4/src/core/GdUnitSettings.gd, addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/ScriptEditorControls.gd, addons/gdUnit4/test/core/GdUnitRunnerConfigTest.gd
After upgrade to Godot.beta17 a lot of runtime errors occurs when running the tests. This happens because of the typed array changes in the beta17.
- Fixed typed array initalisation
- Fixed argument type missmatch of arguments using typed arrays
=> GD-107: Fix runtime errors occuring with Godot beta17 typed Array changes

README.md, addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/asserts/GdUnitObjectAssertImpl.gd, addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/GdUnitClassDoubler.gd, addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd, addons/gdUnit4/src/mocking/GdUnitMockFunctionDoubler.gd, addons/gdUnit4/src/spy/GdUnitSpyFunctionDoubler.gd, addons/gdUnit4/test/asserts/GdUnitAssertImplTest.gd, addons/gdUnit4/test/mocker/GdUnitMockBuilderTest.gd, addons/gdUnit4/test/mocker/GodotClassNameFuzzer.gd, addons/gdUnit4/test/mocker/resources/ClassWithVariables.gd, addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd
With Godot4.RC1 the mock and spy was broken and needs to be fixed.
- add `@warning_ignore("native_method_override")` to mark shadowed core functions as allowed
- temporary fix to skip mock functions with return type enum defined at GlobalScope
- adapt changes of function description to allow enums as return type
=> GD-111: Upgrade GdUnit4 to run with Godot4.RC1

addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitRunnerConfig.gd
The equals had some issues to compare deeply objects where has unsorted dictionarys as parameters
- Use own `obj2dict` to convert a object into a dictionary representation. The dictionary is compared key wise to handle unsorted key/values
- Fix ProjectSettings.get_global_class_list()
- better failure message for `is_equals()` when compare object, if the object has an `_to_string` implemented use it to print the message
=> Improve equals object deep checks

addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/report/GdUnitByPathReport.gd, addons/gdUnit4/src/report/GdUnitHtmlPatterns.gd, addons/gdUnit4/src/report/GdUnitHtmlReport.gd, addons/gdUnit4/src/report/GdUnitReportSummary.gd, addons/gdUnit4/src/report/GdUnitTestCaseReport.gd, addons/gdUnit4/src/report/GdUnitTestSuiteReport.gd, addons/gdUnit4/src/report/JUnitXmlReport.gd, addons/gdUnit4/src/report/XmlElement.gd, addons/gdUnit4/test/core/GdUnitExecutorTest.gd
The report was corruped by using unescaped characters inside the html code
- do html encoding on test-case names
- use single quotes for building test_case_names
- reformat code according code style
=> GD-118: JUnitXMLReport: use HTML encoding for test-case names

.github/actions/unit-test/action.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/core/GdUnitClassDoubler.gd, addons/gdUnit4/src/core/GdUnitExecutor.gd, addons/gdUnit4/src/core/GdUnitMemoryPool.gd, addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/core/GdUnitSignals.gd, addons/gdUnit4/src/core/GdUnitSingleton.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/test/core/GdUnitExecutorTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit4/test/core/GdUnitSingletonTest.gd
Running the `GdUnitCmdTool` ends with an signal 11 and many orphan resource detected
- fixed the signal 11 by using a copy to iterate over singletons before freeing
- when iterating over an array and removing elements during the iteration, godot ended up with signl 11
- moving the func `assert_failed_at` to another posision (very strange results, it crashed for no reason)
- using typed array on `load_testsuites()`
- fix some orphan issues around singleton implementation
- centralize code to finaly cleanup in new `quit` function to avoid orphan nodes
- format touched code according to code style
It still detects orphan nodes see: https://github.com/godotengine/godot/issues/68009
=> GD-120: Fix signal 11 crash when execute tests via `GdUnitCmdTool`

.github/actions/godot-install/action.yml, .github/actions/unit-test/action.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/bin/GdUnitCmdTool.gd
In the current ci-pr WF, the Godot engine runs in headless mode due to missing display and render drivers. Using headless mode only works for tests without UI interactions and will not work with the GdUnit4 SceneRunner. The SceneRunner uses Input.warp_mouse() and Input.parse_input_event() which are not supported in headless mode.
- exit with error 103 if starting the cmd tool with option `--headless`
- remove the headless mode from ci-pr unit test run
- download and install opengl driver if need
- run tests now with option `--display-driver x11 --rendering-driver opengl3 --screen 0`
=> GD-123: Change to rendermode opengl for c-pr

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/core/GdUnitExecutor.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/core/report/GdUnitReport.gd, addons/gdUnit4/src/core/report/GdUnitReportCollector.gd, addons/gdUnit4/test/GdUnitTestSuiteTest.gd
A test case was reported as success when the test case signature contains invalid arguments. The error was only reported by push_error
Mark a invalid test case now as skipped and add a report why.
=> GD-95: Let the test case skip if invalid test arguments used

.github/workflows/ci-pr.yml, README.md, addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitObjectAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitMemoryPool.gd, addons/gdUnit4/src/core/GdUnitSignalAwaiter.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd, addons/gdUnit4/src/matchers/AnyClazzArgumentMatcher.gd, addons/gdUnit4/src/network/GdUnitTcpServer.gd, addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd, addons/gdUnit4/test/core/GdObjectsTest.gd, addons/gdUnit4/test/core/parse/GdFunctionDescriptorTest.gd, addons/gdUnit4/test/mocker/GdUnitMockBuilderTest.gd, addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd
With RC3, RC4, RC3 some regressions are introduced and needs to be addapt to get GdUnit4 running
- fix bug in releasing internal memory store
- fix function doubling according to fixed issue (https://github.com/godotengine/godot/issues/73046)
- remove custom `is_instanceof` and replace it by new engine function `is_instance_of`
- do code formattings
- use new signal code style to connect/disconnect
- use workaround for `GlobalScript` enums (https://github.com/godotengine/godot/issues/73835)
- use workaround for `Timer.timeout.connect` (https://github.com/godotengine/godot/issues/73889)
- use workarount for `Callable.get_method()` (https://github.com/godotengine/godot/issues/73052)
- switch to RC5 on ci-pr WF
=> GD-128: Update GdUnit core to work with Godot.RC5

addons/gdUnit4/plugin.gd
This adds a missing singleton dispose, which made my editor crash on exit.
=> Add missing `GdUnitSignals.dispose()`

addons/gdUnit4/src/core/GdUnitSettings.gd
The `Create Test` was broken because the GdUnit settings contained an invalid initial execution definition template
Use the correct template function to initialize the template settings correctly.
=> GD-150: Create test on a fresh GdUnit4 install results in wrong indent

addons/gdUnit4/src/GdUnitArrayAssert.gd, addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitPackedArrayAssertTest.gd
`assert_array([1, 2, 3, 4, 5]).not_contains([0, 6])`
We want to check if an array does not contain certain values
- Added missing validaiton `not_contains(expected)`
- Resolve error messages by formatting the values correctly
=> GD-164: Extend `assert_array` by `not_contains(expected)` validation

addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/mocking/GdUnitMock.gd, addons/gdUnit4/test/core/GdUnitCommandHandlerTest.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/monitor/GodotGdErrorMonitorTest.gd, addons/gdUnit4/test/network/GdUnitTcpServerTest.gd
The fuction GdUnitMock.on() was renamed to `checked` during migration to Godot4 This was a mistake and must be reverted.
Re-addet the `on` function and set `checked` to deprecated
=> GD-168: Renamed mock function `checked` back to original named `on`

addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitObjectAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitResultAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitBoolAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitDictionaryAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitFloatAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitIntAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitObjectAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitPackedArrayAssertTest.gd, addons/gdUnit4/test/asserts/GdUnitResultAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitStringAssertImplTest.gd
We used a `DefaultValueProvider` by default for all assert implementations but never a custom one except for assert_array and assert_func. This was a holdover from previous refactorings.
Removed the use of the ValueProvider from the normal assert and cleaned up the tests.
=> GD-172: Cleanup GdUnit asserts by remove obsolete `ValueProvider`

addons/gdUnit4/src/ui/parts/InspectorProgressBar.gd, addons/gdUnit4/src/ui/parts/InspectorProgressBar.tscn, addons/gdUnit4/test/ui/parts/InspectorProgressBarTest.gd
An incorrect progress counter was displayed when executing parameterized tests.
- The progress counter increases only at the end of the test and test iterrations are not counted now
- cleanup a bit the progress scene
- add test coverage for the progress bar
=> GD-173: ProgressBar displays an incorrect progress counter when executing parameterized tests.

addons/gdUnit4/src/GdUnitArrayAssert.gd, addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/GdUnitTuple.gd, addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/core/GdArrayTools.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/src/core/GdUnitSignalAwaiter.gd, addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd, addons/gdUnit4/src/extractors/GdUnitFuncValueExtractor.gd, addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd, addons/gdUnit4/test/GdUnitTestCaseTimingTest.gd, addons/gdUnit4/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitDictionaryAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitPackedArrayAssertTest.gd, addons/gdUnit4/test/core/GdArrayToolsTest.gd, addons/gdUnit4/test/core/GdObjectsTest.gd
We want to compare array elements by object reference.
- assert_array now supports all array types
- added verifications
- is_same
- is_not_same
- contains_same
- contains_same_exactly
- contains_same_exactly_in_any_order
- not_contains_same
- improve the failure messages by printing typed arrays
- moved all array util functions into new class `GdArrayTools`
- small cleanups
=> GD-164: Extend array assert by same validation functions

addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd, addons/gdUnit4/test/core/GdObjectsTest.gd, addons/gdUnit4/test/spy/GdUnitSpyTest.gd
When a tester try to spy on a singleton an parser error is shown, but it should push an error do inform is not allowed to spy on a singleton
Added validation on spy builder to verify if the given instance a singleton and stop building a spy on it
=> GD-181: Don't allow spy on singletons

addons/gdUnit4/src/asserts/GdUnitVectorAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitVectorAssertImplTest.gd
The validation uses the standard compare operators <= and >= where not pass to test for equal approx
Add your own comparison to verify
=> GD-182: Fix `assert_vector.is_equal_approx`

addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/monitor/GdUnitMonitor.gd, addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/test/monitor/GodotGdErrorMonitorTest.gd
When a user configures a custom log_path, the push_error notifications are not tracked.
- using full log_path instead of customized log path building.
- add integration test coverage
- create the monitor only at test execution
=> GD-186: Report `push_error` as failure is not working if custom `log_path` is configured

addons/gdUnit4/src/ui/parts/InspectorTreePanel.tscn
It would be cool to see the first error in full. This helps fixing the first bug faster.
(not sure this one helps)
=> GD-197: Show test errors in full.

addons/gdUnit4/plugin.cfg, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/ParameterizedTestCaseTest.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd
The GdScriptParser had problems with strings containing brackets and got stuck.
- fix parser to not tokenize strings and string blocks for brackets 
- Fixed function signature parsing so that spaces, tabs, and line breaks are not lost before merging.
=> GD-213: Fix GdScript parser to handle string blocks

.github/actions/godot-install/action.yml
TuxFamily is currently down (again) and also slow. Because TuxFamily is down, the latest Godot release cannot be uploaded and is therefore not available to this action.
Downloading from GitHub is faster, more reliable and therefore reduces GitHub Action runtime
This changes the default download host from TuxFamily to GitHub.
=> Replace download host for Godot with GitHub

.github/actions/publish-test-report/action.yml, .github/actions/upload-test-report/action.yml, .github/workflows/ci-dev.yml, .github/workflows/ci-pr.yml, README.md, addons/gdUnit4/bin/ProjectScanner.gd, addons/gdUnit4/plugin.gd, addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit4/src/core/GdUnitTools.gd, project.godot
We want to support the latest Godot version v4.1.1
- update project to v4.1.1
- add Godot 4.1, 4.1.1 to ci-pr and ci-dev workflows
- update README.md
- fix crash by remove the temporary workaround introduced by https://github.com/MikeSchulze/gdUnit4/pull/137
- fix crash by do not print messages on plugin `_exit_tree` (https://github.com/godotengine/godot/issues/79379)
```
malloc(): mismatching next->prev_size (unsorted)
Aborted (core dumped)
Error: Process completed with exit code 134.
```
=> GD-224: Update project to Godot 4.1.1

addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd, addons/gdUnit4/test/core/GdUnitSignalAwaiterTest.gd
When try to use the `monitor_signals` on a Resource it fails by a `Invalid get index 'tree_exiting' (on base: 'Resource (ExampleResource)').`
- fixed by test is given emitter from type `Node` before connect to `tree_exiting`
- relase at testsuite end all monitored connected signal
=> GD-222: Fix error on SignalCollector when emitter is not a Node

addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/resources/SoundData.txt, addons/gdUnit4/test/mocker/resources/AdvancedTestClass.gd
I dit a replacement of exist mach variable patterns by if/else to based on Godot issue https://github.com/godotengine/godot/issues/66999
- Replace back the if/else by match construct
- fix a warning of unused variable at `AdvancedTestClass`
=> GD-3: `GdScriptParser` use match instead of if/else

addons/gdUnit4/src/ui/GdUnitFonts.gd, addons/gdUnit4/test/ui/GdUnitFontsTest.gd
We see an error `res://addons/gdUnit4/src/ui/GdUnitFonts.gd:38 - Invalid set index 'font_data' (on base: 'FontFile') with value of type 'FontFile'.` on linux systems when activating the plugin
The property `font_data` was removed and the error was just ignored.
- Rewrite the font loader by load the font and duplicate and set the new font size.
- Renamed to better related name
- Add test coverage
=> GD-233: Fix font loading error on linux systems

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/thread/GdUnitThreadManager.gd, addons/gdUnit4/src/report/GdUnitByPathReport.gd, addons/gdUnit4/src/report/GdUnitHtmlPatterns.gd, addons/gdUnit4/src/report/GdUnitHtmlReport.gd, addons/gdUnit4/src/report/GdUnitReportSummary.gd, addons/gdUnit4/src/report/GdUnitTestCaseReport.gd, addons/gdUnit4/src/report/GdUnitTestSuiteReport.gd, addons/gdUnit4/src/report/JUnitXmlReport.gd, addons/gdUnit4/test/GdUnitTestCaseTimingTest.gd, addons/gdUnit4/test/core/GdUnitToolsTest.gd
The cmd tool was not reporting failures from test hooks e.g `after` and the test was reported as success
- failures during test hooks are now reported and the suite is marked as failed
- fix html test report, add Test hook failures if occurs
- replace usage of RichTextLabel to normalize bbcode and replaced by regex replacement
=> GD-234: CmdTool report failures for all test hooks

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/core/GdUnitExecutor.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/report/GdUnitHtmlReport.gd, addons/gdUnit4/test/asserts/GdUnitGodotErrorAssertImplTest.gd, addons/gdUnit4/test/core/GdUnitExecutorTest.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/core/resources/testsuites/TestCaseSkipped.resource, addons/gdUnit4/test/core/resources/testsuites/TestSuiteSkipped.resource
We want to skip a test-case or entire test-suite
Add new test arguments
* do_skip as runtime expression
* skip_reason as String
```gdscript
func test_case1(do_skip=true, skip_reason="do not run this"):
pass
```
* fix cmd_tool to report skipped test-suites
* remove `skip` function from TestSuite class
* handle skipped test-shuite on executor
* extends test-suite scanner to handle the new skip arguments
=> GD-242: Add runtime argument to skip the entire test-suite or test-case

addons/gdUnit4/runtest.cmd
The 'runtest.cmd' scripts still contains the '--no-window' argument where is changed with Godot4 to `--headless`
Use `--headless` argument to execute `GdUnitCopyLog` in headless mode
=> GD-255: Fix `runtest.cmd` to run `GdUnitCopyLog` in headless mode

.github/workflows/ci-pr-example.yml
Users want to get a fast introduce how to run GdUnit4 in a CI workflow.
Provide a minimized example ci workflow to run tests on a PR.
=> GD-262: Add simple ci workflow example

addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/asserts/GdUnitAssertions.gd, addons/gdUnit4/src/core/GdUnitExecutor.gd
The asserts was first loaded (lazy) when a test is executed, this distorts the test execution time
Preload all gdunit assets that are initially loaded when the executor is created. Each next lazy load will then take the script out of the cache.
* before fix
* after fix
=> GD-269: Lazy loading of gdunit assets affects test case execution time.

addons/gdUnit4/src/core/execution/GdUnitMemoryObserver.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestSuiteExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/fuzzed/GdUnitTestCaseFuzzedExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/parameterized/GdUnitTestCaseParameterizedExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/single/GdUnitTestCaseSingleExecutionStage.gd, addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd, addons/gdUnit4/src/extractors/GdUnitFuncValueExtractor.gd, addons/gdUnit4/src/report/GdUnitByPathReport.gd, addons/gdUnit4/src/report/GdUnitHtmlReport.gd, addons/gdUnit4/src/report/GdUnitTestCaseReport.gd, addons/gdUnit4/test/asserts/GdUnitArrayAssertImplTest.gd, addons/gdUnit4/test/core/parse/GdDefaultValueDecoderTest.gd
GdUnit4 contains some script errors such as:
- redundant awaits
- shadowing an already-declared function at line xxx
- Fix error messages to rid the log of script errors generated by the GdUnit4 framework
- Fix bug in the new executor, do not execute skipped test cases
- Disable the leaked instance gurad for now, it let the engine randomly crash at exit and needs an deeper investigate to fix
=> Cleanup script erros

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd
If a test fails due to a combination of warnings and errors, the inspector displays a warning instead of an error.
Fix the state handling by not overwriting a higher state if it exists.
testcase2 has orphan warnings and is failing
=> GD-278: Fix inspector item state.

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/bin/ProjectScanner.gd, addons/gdUnit4/src/core/GdUnitRunner.gd, gdUnit4.csproj
The C# GdUnit4 API package is renamed to gdUnit4.api and the serialization of TestEvent has changed
- Update the project to use NuGet package 'gdUnit4.api'
- Update `PublishEvent` handled incoming data as dictionary
=> Update to new GdUnit4 CSharp API package

addons/gdUnit4/src/core/GodotVersionFixures.gd, addons/gdUnit4/src/core/parse/GdFunctionArgument.gd
Fixing a syntax error when opening `GdUnit4` in Godot 4.2 stable, closes https://github.com/MikeSchulze/gdUnit4/issues/286
Renames `convert()` to [`type_convert()`](https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-type-convert).
```diff
func default() -> Variant:
-       return convert(_default_value, _type)
+       return type_convert(_default_value, _type)
```
=> GD-286: Update project to Godot 4.2

addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit4/test/core/parse/GdFunctionDescriptorTest.gd, addons/gdUnit4/test/core/resources/scenes/input_actions/InputEventTestScene.gd, addons/gdUnit4/test/core/resources/scenes/input_actions/InputEventTestScene.tscn
A user reported input actions not work.
- Add test coverage to verify it works as expected
- fix small scene memory free bug.
=> GD-292: Add test coverage to simulate input event as actions

addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/core/GdUnitSignalCollector.gd, addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd
The `signal_assert` was not able to collect many signals at the same time, each assert call resulted in a cleanup of the collected signals, so the next `assert_signal` failed
Correct cleanup of collected signals, clean up only the signals used by the specific assert call
=> GD-296: Fix `signal_assert` to collect many signals at same time

addons/gdUnit4/src/asserts/GdUnitStringAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitStringAssertImplTest.gd
We want to test not only against `String` with Godot 4.x `StringName` was introduced.
- Allow to use `StringName` on `assert_str()`
- improve test coverage
=> GD-299: Respect `StringNames` on `assert_str()`

.github/workflows/ci-dev.yml, .github/workflows/ci-pr.yml, .github/workflows/unit-tests.yml, README.md
We need to cover Godot 4.2.1 and upcoming Godot 4.3 on CI.
- Add Godot 4.2.1 and 4.3-dev to CI-PR
- Add Godot 4.2.1 to CI-DEV
=> GD-301: Add Godot `4.2.1` to CI

.github/workflows/ci-dev.yml, .github/workflows/ci-pr.yml, README.md, addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/plugin.gd, addons/gdUnit4/src/asserts/GdUnitGodotErrorAssertImpl.gd, addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/core/execution/GdUnitExecutionContext.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseAfterStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseBeforeStage.gd, addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/test/asserts/GdUnitGodotErrorAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitGodotErrorWithAssertTest.gd, addons/gdUnit4/test/monitor/GodotGdErrorMonitorTest.gd, addons/gdUnit4/test/spy/GdUnitSpyTest.gd
If a test case loads/executes a script and contains script errors, and it was tested with `assert_error`, it was still reported as an error.
- Revision of `GodotGdErrorMonitor`
- create the monitor in the execution context to get full control over the test execution time
- filter out tested errors when `assert_error` is used
- set minimum required Godot version to 4.1.x
=> GD-303: Do not report script errors when if already tested by using `assert_error`

.github/workflows/ci-pr.yml, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitObjectInteractionsTemplate.gd, addons/gdUnit4/src/matchers/AnyClazzArgumentMatcher.gd, addons/gdUnit4/src/matchers/ChainedArgumentMatcher.gd, addons/gdUnit4/src/matchers/GdUnitArgumentMatcher.gd, addons/gdUnit4/src/matchers/GdUnitArgumentMatchers.gd, addons/gdUnit4/src/mocking/GdUnitMockImpl.gd, addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd, addons/gdUnit4/src/spy/GdUnitSpyImpl.gd, addons/gdUnit4/test/mocker/GdUnitMockBuilderTest.gd, addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd
The mocking and spy fails if the project settings are set to `debug/gdscript/warnings/untyped_declaration=Error`.
- Fixed missing/invalid type errors in mock and spy template and object interaction template
- set `@warning_ignore("untyped_declaration")` to doubled functions as it fails with Godot 4.2.x
=> GD-312: `Mock` and `Spy` should generate type save doubles

addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/matchers/AnyArgumentMatcher.gd, addons/gdUnit4/src/matchers/AnyBuildInTypeArgumentMatcher.gd, addons/gdUnit4/src/matchers/AnyClazzArgumentMatcher.gd, addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd, addons/gdUnit4/test/matchers/AnyArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/AnyBuildInTypeArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/AnyClazzArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/ChainedArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/CustomArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/GdUnitArgumentMatchersTest.gd
Sometimes we want to test for an emitted signal, but are not interested in the signal arguments and therefore want to use an argument matcher.
- extends the `equals` implementation to deal with argument matchers in general.
=> GD-307: Allow argument matchers on `assert_signal` arguments

_advanced_testing/cmd.md
Fix typo and incorrect commands.
Easier to read and follow.
Replaces https://github.com/MikeSchulze/gdUnit4/pull/310
=> Fix typos in documentation for cmd

addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd
The simulate function `simulate_mouse_move_relative` was confusing the tester and has not work as described. It would be simpler to define a time to move instead of a speed with pixels/second.
* rework the  `simulate_mouse_move_relative` to using a time parameter.
* added `simulate_mouse_move_absolute` to move the mouse to an absolute position
```
func simulate_mouse_move_relative(relative: Vector2, time: float = 1.0, trans_type: Tween.TransitionType = Tween.TRANS_LINEAR) -> GdUnitSceneRunner:
func simulate_mouse_move_absolute(position: Vector2, time: float = 1.0, trans_type: Tween.TransitionType = Tween.TRANS_LINEAR) -> GdUnitSceneRunner:
```
=> GD-323: Fix `simulate_mouse_move_relative` to use a time parameter instead of speed as pixels peer seconds

addons/gdUnit4/src/cmd/CmdCommandHandler.gd, addons/gdUnit4/test/cmd/CmdArgumentParserTest.gd
The use of multiple `--add` commands was incorrect and resulted in no tests being found.
Use method arguments to evaluate which function callback needs to be called `callv` vs `call`
=> GD-337: fix cmd tool to accept multiple `--add` commands

addons/gdUnit4/src/network/GdUnitTcpServer.gd, addons/gdUnit4/src/report/template/folder_report.html, addons/gdUnit4/src/report/template/index.html, addons/gdUnit4/src/report/template/suite_report.html
Some reports still reference gdUnit3 when rendered. There are also some spelling errors (e.g., "Comming" instead of "Coming".
I updated the version in the templates and fixed some spelling errors I found
=> GD-348: Change gdUnit3 to gdUnit4 in report templates, fix some spelling errors

addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit4/test/core/resources/scenes/simple_scene.gd, addons/gdUnit4/test/core/resources/scenes/simple_scene.tscn
A user runs into an error of scene is not valid during test execution by using `simulate_mouse_move_relative` without the `await`
- Added test to reproduce the issue
- made the runner more robust for such exceptional cases
- improve the inline documentation to be more present in the fact to use `await`
=> GD-356: SceneRunner made more robust

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/src/ui/parts/InspectorTreePanel.tscn
There were several problems with the context menu, which needs to be redesigned
- The context menu was not placed correctly when using multiple screens.
- the highlighting of context menu items did not work
- the implementation was based on a lack of knowledge
Complete redesign of the context menu
- respect the screen position
- uses `PopupMenu` instead of `PopupPanel `
- add icons to the context menu
=> GD-353: Redesign GdUnit inspector context menu

addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/core/execution/stages/parameterized/GdUnitTestCaseParameterizedTestStage.gd, addons/gdUnit4/test/core/ParameterizedTestCaseTest.gd
With https://github.com/MikeSchulze/gdUnit4/issues/359 i introduced a bug and the test resolving was broken.
fixed the test name resolving to handle multiline test arguments
=> GD-363: Follow-up to fix errors on parameterized test naming resolving

addons/gdUnit4/runtest.cmd, addons/gdUnit4/runtest.sh
This ensures that settings of `Exclude Addons` for strict type checking on the project is honored.
Fixes #365
This fixes the issue with the Github actions failing because the project settings have strict type checking on but have `Exclude Addons` settings turned on.
Change runtest.sh and runtest.cmd to use the res:// URL format so that the Exclude setting is properly applied.
I was able to test the Linux(runtest.sh) version here-  https://github.com/vikerman/GDUnitTest/actions/runs/8217131139
but not the Windows version (runtest.cmd).
=> Refer to the scripts using res:// URL.

addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/mocker/CustomEnums.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/mocker/resources/ClassWithEnumReturnTypes.gd
The mock was build invalid for classes containing functions with enum return types. It results into a runtime error.
- Fix script parser to handle enum return types.
- Add test coverage for all variants of enums (class enum, internal class enums, external class enums)
=> GD-370: Mock a class with functions return type enum results in an error Parser Error: Cannot return a value of type "null"

addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/GdUnitObjectInteractions.gd, addons/gdUnit4/src/core/GdUnitObjectInteractionsTemplate.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/mocking/GdUnitMockImpl.gd, addons/gdUnit4/test/mocker/GdUnitMockBuilderTest.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd
mocking a class with functions has return type enum was spamming in warnings of type `int_as_enum_without_match` and `int_as_enum_without_cast`
- Do add a ignore warning to the mocked function with return type enum to hide such warnings.
- Improved the default enum detection to return a valid enum value
- Fixes also warnings about shadowed variables by rename all mock intern used variables by adding two underscores
=> GD-374: Improve mocking of fuctions with return type enum

addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd
The test spams push errors based on `_reset_input_to_default` is called when releasing the runner. This can happen when the used scene itself was already freed for some circumstances.
instead of calling `_reset_input_to_default` at `NOTIFICATION_PREDELETE` we register it for scene signal `child_exiting_tree` to detect the scene is removed and run `_reset_input_to_default`
=> GD-373: Fix invalid push error notifications on scene runner at `_reset_input_to_default`

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/cmd/CmdCommandHandler.gd
For certain reasons, we would like to run the test in headless mode, but the cmd tool does not allow this and ends with an error message.
Added new option `--ignoreHeadlessMode` to ignore this fact and print only a warning and continue the processing.
=> GD-380: Add cmd option to allow running with `--headless` mode

addons/gdUnit4/plugin.cfg, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/core/parse/GdUnitTestParameterSetResolverTest.gd, addons/gdUnit4/test/mocker/resources/ClassWithCustomFormattings.gd, gdUnit4.csproj
When we put comments in the test function signature, the test case was not successfully parsed.
- we remove all comment during parsing to finally extract the function signature.
- increase GdUnit4 version to 4.2.4
- update C# project dependencies
=> GD-383: Fix parsing of test with comments in the signature

addons/gdUnit4/runtest.sh
So that GODOT_BIN paths with spaces can be used.
Surround GODOT_BIN usage with quotes.
#385
=> GD-385: Fix runtest.sh not working for GODOT_BIN with spaces

.github/workflows/ci-pr.yml, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/core/resources/scan_testsuite_inheritance/by_class_name/BaseTest.gd, addons/gdUnit4/test/core/resources/scan_testsuite_inheritance/by_class_name/ExtendedTest.gd
https://github.com/MikeSchulze/gdUnit4/issues/389
When the scanner is building the function descriptors, it was using the list of tests and adding the `before` function to scan. The list to scan was not a copy and results into side effect of the original test list. Fixed by using a copy before adding the `before` function extended the existing test coverage for test suite inheritance to include the `before` on the base test suite.
=> GD-389: The inheritance of a base test class leads to an incorrect test case list.

addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/core/resources/testsuites/TestSuiteWithoutTests.gd
https://github.com/MikeSchulze/gdUnit4/issues/390
We do not collect test suites that do not contain tests during test suite detection and instead notify through a push warning.
=> GD-390: A test suite without tests leads to be listed as test suite with 0 test cases in the Test Explorer

addons/gdUnit4/src/GdUnitAwaiter.gd, addons/gdUnit4/src/GdUnitConstants.gd, addons/gdUnit4/src/asserts/GdAssertReports.gd, addons/gdUnit4/src/asserts/GdUnitFailureAssertImpl.gd, addons/gdUnit4/test/GdUnitAwaiterTest.gd, addons/gdUnit4/test/asserts/GdUnitFuncAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit4/test/core/GdUnitSignalAwaiterTest.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/core/parse/GdUnitTestParameterSetResolverTest.gd
https://github.com/MikeSchulze/gdUnit4/issues/392
* Removed the outdated `assert_failed_at` helper functions from the test suites and switch to `assert_failure_await` to avoid unsafe usage of `GdAssertReports.expect_fail()` An unsafe use of `GdAssertReports.expect_fail()` was resulting into failures not reported.
* renamed `expect_fail` and mark as private
* move and convert finally the failing test to `GdUnitTestParameterSetResolverTest#test_validate_test_parameter_set`
The failure is now reported as expected
=> GD-392: Fixes missing failure reporting when a test uses unsafe `GdAssertReports.expect_fail()`

.runsettings, .runsettings-ci, addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/plugin.gd, addons/gdUnit4/src/mono/GdUnit4CSharpApi.cs, addons/gdUnit4/test/mono/GdUnit4CSharpApiTest.cs, gdUnit4.csproj, project.godot
https://github.com/MikeSchulze/gdUnit4/issues/396
* update `gdUnit4.api` dependency to latest gdUnit4Net version
* added dependencies to support the test adapter
* Use based on `gdunit4.api` version the `GdUnit4MonoAPI` or `GdUnit4NetAPI` to call the API
=> GD-396: Update C# API bridge to `gdUnit4Net` v4.2.2

_faq/vstest-adapter.md
Rider would ignore the GODOT_BIN environment variable, it has its own up-to-date knowledge about the Godot executable location.
https://github.com/JetBrains/godot-support/blob/net241/resharper/src/UnitTesting/GodotGdUnitTestRunnerHost.cs#L24-L25
=> Add a note about Rider and GODOT_BIN to the adapter documentation

addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit4/test/core/resources/scenes/input_actions/InputEventTestScene.gd
Closes #401 
*(as suggested on Discord)*
Using generic action events is better as unit tests don't get tied to a specific key in the project for any given action. Furthermore, it also support actions that only have controller inputs.
Adds methods for a scene runner to also support action events.
~~Oddly though, I'm not getting any luck in implementing unit testing for this feature on the addon's tests. This works as expected on the tests in my project, but for some reason `Input.is_action_pressed` AFAICT never returns true on the unit tests. I also see there is a test `test_simulate_keypressed_as_action` doing something similar and is also failing though.~~ EDIT: Fixed by @MikeSchulze :heart:
=> GD-401: Support action input events on scene runner

addons/gdUnit4/src/GdUnitStringAssert.gd, addons/gdUnit4/src/asserts/GdUnitResultAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitStringAssertImplTest.gd
There is a typo at `func has_length(lenght: int, comparator: int = Comparator.EQUAL) -> GdUnitStringAssert:`
fix the typo
=> GD-399: Fix typo for first argument in `GdUnitStringAssert#has_length` 

.github/workflows/ci-dev.yml, .github/workflows/ci-pr-example.yml, .github/workflows/ci-pr.yml, README.md, addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GodotVersionFixures.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd
Godot v4.2.2 and V4.1.4 are out
- update the workflows and added support for Godot v4.2.2 and V4.1.4
- fix workflow errors using invalid matrix parameters
- fix failing test related to the Godot global_position fix https://github.com/godotengine/godot/pull/88473
=> GD-405: Update workflows to support latest Godot versions

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit4/src/core/GdUnitRunnerConfig.gd, addons/gdUnit4/src/report/GdUnitHtmlReport.gd, addons/gdUnit4/src/report/GdUnitReportSummary.gd, addons/gdUnit4/src/report/GdUnitTestCaseReport.gd, addons/gdUnit4/src/report/GdUnitTestSuiteReport.gd, addons/gdUnit4/test/asserts/GdUnitDictionaryAssertImplTest.gd, addons/gdUnit4/test/core/GdUnitRunnerConfigTest.gd, addons/gdUnit4/test/core/resources/GdUnitRunner_with_skipped_testsuites.cfg
https://github.com/MikeSchulze/gdUnit4/issues/409
There was a comprehensive refactoring of the test execution and the cmd tool was forgotten in the process
- fix test suite skipped when is excluded in the runner config
- fix test report summary, it was shown wrong test count
- improve final report summary to show skipped vs executed information
- fix minor assert_dictionary issue, do use the correct error message for missing keys
* starting messages
* skipped test suite
* partial skipped test suite
* report summary
=> GD-409: Fix do skip excluded test suites by runner configuration

_advanced_testing/sceneRunner.md, _faq/solutions.md, _first_steps/install.md, index.md
- update `SceneRunner`, added `simulate_action_pressed`, `simulate_action_press`, `simulate_action_release`
- added problems and solution page
- added hint for plugin installing needs restart
=> GD-402: Update documentation to GdUnit4 v4.2.5

addons/gdUnit4/plugin.cfg, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/spy/GdUnitSpyTest.gd, addons/gdUnit4/test/spy/UnitPreset.gd
The spy runs into an error when try to spy on an instance where has an Enum argument in the constructor.
Fixed the spy builder by evaluate the arg_type is an Enum and set the respective argument type.
=> GD-413: Allow to spy on a class with enum as constructor argument

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/test/spy/GdUnitSpyTest.gd
The publishing test report is failing on forked repository.
- use gdunit4-action@v1.0.6 and disable report publishing
- add extra workflow to run after `ci-pr` to publish the reports afterward.
=> GD-306: Do run `gdunit-action` on CI-PR without publish report

.gitattributes
I can't tell for sure but it seems like `.runsettings*` and `.gdlintrc` paths were included in the release by mistake since the `.gitattributes` is an excluded list.
The current `.gitattributes` structure looks difficult to maintain. If `.runsettings*` and/or `.gdlintrc` should be kept in the final release, this PR can easily be updated to include them explicitly.
I flipped the `.gitattributes` around to be an includes list by excluding everything first. This approach should keep it more maintainable as you may add other files to the project later that are not needed in the final release.
This is testable by running this command against this branch:
`git archive --format=tar improve-gitattribute | gzip > <replace-this-with-a-path>`
=> Simplify `.gitattributes`

.github/workflows/gdlint.yml, addons/gdUnit4/bin/GdUnitBuildTool.gd, addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/bin/GdUnitCopyLog.gd, addons/gdUnit4/bin/ProjectScanner.gd, addons/gdUnit4/src/cmd/CmdArgumentParser.gd, addons/gdUnit4/src/cmd/CmdCommand.gd, addons/gdUnit4/src/cmd/CmdCommandHandler.gd, addons/gdUnit4/src/cmd/CmdConsole.gd, addons/gdUnit4/src/cmd/CmdOption.gd, addons/gdUnit4/src/cmd/CmdOptions.gd, addons/gdUnit4/src/core/GdUnitRunnerConfig.gd, addons/gdUnit4/src/core/event/GdUnitEvent.gd, addons/gdUnit4/src/report/GdUnitByPathReport.gd, addons/gdUnit4/src/report/GdUnitHtmlReport.gd, addons/gdUnit4/src/report/GdUnitReportSummary.gd, addons/gdUnit4/src/report/GdUnitTestCaseReport.gd, addons/gdUnit4/src/report/GdUnitTestSuiteReport.gd, addons/gdUnit4/src/report/JUnitXmlReport.gd, addons/gdUnit4/src/report/XmlElement.gd
see https://github.com/MikeSchulze/gdUnit4/issues/427
made code cleanup at:
- bin/
- src/cmd/
- src/report/
=> GD-427: Do use typed variables and arguments (part1)

addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/core/resources/scan_testsuite_inheritance/plugin/inspector_plugin.gd, addons/gdUnit4/test/core/resources/scan_testsuite_inheritance/plugin/plugin.cfg, addons/gdUnit4/test/core/resources/scan_testsuite_inheritance/plugin/preload.gd, addons/gdUnit4/test/core/resources/scan_testsuite_inheritance/plugin/testplugin.gd
see https://github.com/MikeSchulze/gdUnit4/issues/440
- check if the script to scan extends from `GdUnitTestSuite` without using the resource loader to avoid preload issues
=> GD-440: Improve test suite scanner to ignore non test-suite scripts

addons/gdUnit4/src/ui/GdUnitInspector.gd
When undock the `gdunit` inspector, there are errors shown and the `gdunit` context menu is duplicated. These errors results because the register/unregister of context menus is done in the `_enter_tree` and `_exit_tree` block where are called again when undock and dock the inspector
- moved the registration of context menus to the `_ready` block
- moved unregister of context menus to the `_notification` block at state NOTIFICATION_PREDELETE
=> GD-443: Fix errors when dock undock the `gdunit` inspector

addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/core/resources/naming_conventions/extends_on_same_line.gd
When a test script is using `extends` on the same line as the `class_name` the parser do resolves an invalid class name. `class_name ClassNameExtendsInSameLine extends Resource` is resolved as `ClassNameExtendsInSameLineextendsResource`
- fixed the parser to extract the right class name.
=> GD-451: Fix script parser to extracting the correct class name

addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/src/core/parse/GdUnitTestParameterSetResolver.gd, addons/gdUnit4/test/core/ParameterizedTestCaseTest.gd, addons/gdUnit4/test/core/parse/GdFunctionArgumentTest.gd
The test was marked as skipped when the `test_parameters` contains external const array values.
```
const _data1 := ["aa"]
const _data2 := ["bb"]
@warning_ignore("unused_parameter")
func test_with_extern_const_parameter_set(value :String, test_parameters := [_data1, _data2]) -> void:
```
fix the parameterized argument parsing
=> GD-465: Parameterized tests are skipped with const Array values

_csharp_project_setup/vstest-adapter.md
Add info to install required minimum version of plugin `godot-support`
=> GD-470: Improve the C# setup Rider guide

addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/cmd/CmdConsole.gd, addons/gdUnit4/src/core/GdDiffTool.gd, addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/fuzzers/StringFuzzer.gd, addons/gdUnit4/src/network/GdUnitTcpClient.gd, addons/gdUnit4/src/network/GdUnitTcpServer.gd, addons/gdUnit4/test/core/GdDiffToolTest.gd, addons/gdUnit4/test/fuzzers/StringFuzzerTest.gd, addons/gdUnit4/test/network/GdUnitTcpServerTest.gd
The test messages losing UTF8 characters during reporting. This results for converting UTF8 strings via  `to_utf8_buffer` and `get_string_from_utf8`
fixes by replace `get_string_from_utf8` and `to_utf8_buffer` by the utf8 derivate
=> GD-471: Support `UTF8` characters on reporting failure messages

addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/test/core/parse/GdFunctionArgumentTest.gd
See https://github.com/MikeSchulze/gdUnit4/issues/468
We first trim the input by removing edges and surrounding brackets and then iterate over possible parameters
=> GD-468: Fix prameterized test argument parsing

addons/gdUnit4/src/ui/GdUnitUiTools.gd
On macOS there are errors on startup.
```
Godot Engine v4.2.1.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
Invalid image: null
core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
Invalid image: null
core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
Invalid image: null
core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
Invalid image: null
core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
Invalid image: null
core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
Invalid image: null
Loading GdUnit4 Plugin success
```
- disable the image size check when merge icons because it has different size on macOS 16vs32 pixels
=> GD-486: Fix image size errors at startup

addons/gdUnit4/src/ui/GdUnitUiTools.gd, addons/gdUnit4/test/ui/GdUnitUiToolsTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/490
Resizes the first image to the same size as the second image before it is merged
=> GD-490: Fix icon image size errors when using custom editor display scale

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/plugin.gd, addons/gdUnit4/src/core/GdUnitSignals.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/GodotVersionFixures.gd, addons/gdUnit4/src/core/command/GdUnitCommandHandler.gd, gdUnit4.csproj, project.godot
The Godot editor crashes if the GdUnit4 plugin enabled at exit.
- Extend the hotfix to run also on Linux systems
- Does not execute the plugin code if the project has the gdunit4 plugin enabled but is running in a test environment. This prevents the loading of UI components that are not required if the Godot program is executed without editor mode.
- Does not execute the scheduled test discovery when you run the cmd tool to avoid overlaps during test execution.
=> GD-491: Fix Godot editor crash for Linux systems at exit

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
The error occurs because splitting a path by an empty string is invalid and results later in an index out of bounds error
Fixed by set the root_folder back to the resource root before splitting into parts for the tree
=> GD-494: Fix test discovery error when test root path is set to empty

addons/gdUnit4/src/core/discovery/GdUnitTestDiscoverer.gd
see https://github.com/MikeSchulze/gdUnit4/issues/497
Moved the time-consuming scanning part into an extra thread to not block the main thread anymore.
=> GD-497: Execute the test discovery in an additional thread so as not to block the main thread.

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/core/GdUnitSignals.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/LocalTime.gd, addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/src/ui/menu/GdUnitContextMenuItem.gd, addons/gdUnit4/test/core/GdObjectsTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/core/parse/GdDefaultValueDecoderTest.gd, addons/gdUnit4/test/mocker/GodotClassNameFuzzer.gd, addons/gdUnit4/test/mocker/resources/scenes/Spell.gd, addons/gdUnit4/test/mocker/resources/scenes/TestScene.gd, project.godot
see https://github.com/MikeSchulze/gdUnit4/issues/501
- added Godot 4.3.beta1 to the CI workflow
- fixed enum default value warnings
- fixed unused signal warnings
- fixed missing test-suite icon resource
- fixed failing input action tests
- use typed values in GdObject to avoid bug https://github.com/godotengine/godot/issues/93193
- add `TYPE_PACKED_VECTOR4_ARRAY` constant to be used on Godot versions less than 4.3 (is introduced with beta1)
=> GD-501: Prepare GdUnit4 for Godot 4.3.beta1

addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/ScriptEditorControls.gd, addons/gdUnit4/src/ui/menu/ScriptEditorContextMenuHandler.gd
https://github.com/MikeSchulze/gdUnit4/issues/506
- simplify adding the `ScriptEditorContextMenuHandler`
- problematic "Dispose" functionality removed, the handler is now released via the standard Godot three-node free mechanism
=> GD-506: Revisit the ScriptEditorContextMenuHandler added to the root node

addons/gdUnit4/plugin.gd, addons/gdUnit4/src/ui/GdUnitInspector.tscn
see https://github.com/MikeSchulze/gdUnit4/issues/505
- Moved server loading to the inspector to be handled by the Godot tree itself for adding and releasing the resources
- removed server loading from the `plugin.gd`
=> GD-505: Move GDUnitServer instantiating and releasing to GdUnitInspector

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/plugin.cfg
- set new plugin version to v4.3.3
- update bug report template
- add Godot 4.3-beta2 to the CI workflow
=> Bump to GdUnit4 v4.3.3

addons/gdUnit4/plugin.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/discovery/GdUnitTestDiscoverGuard.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/GdUnitTestResourceLoader.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd, addons/gdUnit4/test/core/discovery/resources/DiscoverExampleTestSuite.cs, addons/gdUnit4/test/core/discovery/resources/DiscoverExampleTestSuite.gd
see https://github.com/MikeSchulze/gdUnit4/issues/517
- added rebuild cs scripts before run discovery
- fixed invalid script path resolving by using `localize_path` to convert cs script paths
- fixes test suite scanner to run on Script class to accept `GDScript` and `CSharpScript`
=> GD-517: Fix test discovery guard fails on `CSharpScript` tests when editing

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
see https://github.com/MikeSchulze/gdUnit4/issues/518
- Use of `localize_path` for all resource paths used (cs scripts contain the system path)
- `create_tree_item()` has been corrected to split the test path into tree items depending on the view mode.
- It takes into account if the test root folder does not exist to split the full path then
=> GD-518: Fix run/debug of CS tests via the context menu fails

.github/ISSUE_TEMPLATE/bug_report.yml, addons/gdUnit4/plugin.cfg, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
A user reported an script error ` res://addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd:880 - Cannot call method 'get_meta' on a null value.` It can only happen when no test/test suite is selected in the inspector.
Added a null check to avoid this kind of error
=> GD-529: Fix null value access in the inspector.

addons/gdUnit4/src/GdUnitAssert.gd, addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitAssertImplTest.gd
The  `assert_not_yet_implemented` reports the wrong line number
- Renaming of the internally called assert function from `test_fail` to `do_fail` in order not to collide with the error line detection in `GdUnitAssertions.get_line_number()`.
- add missing test coverage
=> GD-531: Fix `assert_not_yet_implemented` reports the wrong line number

addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd
see https://github.com/MikeSchulze/gdUnit4/issues/533
We do use a default color if the editor settings have the default color not set.
=> GD-533: Fixes script error in `TestSuiteTemplate` when Godot was installed for the first time

addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/test/core/GdObjectsTest.gd, addons/gdUnit4/test/core/resources/scenes/SceneWithEmbeddedScript.tscn
see https://github.com/MikeSchulze/gdUnit4/issues/537
fixed the `obj2dict` by add handling built-in scripts to extract the class_name and class_path
=> GD-537: Fix comparing objects containing built-in script type members

addons/gdUnit4/src/core/GdUnitSettings.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.gd, addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.tscn, addons/gdUnit4/test/core/GdUnitSettingsTest.gd, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd
Hi, this PR improves the settings dialogue UI, making it significantly more compact, and IMHO, also easier to understand and nicer to look at.
Before:
After:
The changes are split into three commits
1. Remove the value sets of settings from the user-facing help strings. Fixes #539 
2. Improve the wording of the help strings themselves (more detailed description in the commit message). Fixes #540 
3. Improved sizing logic for the grid views displaying the settings, meaning less space is wasted, and huge amounts of unused space don't make the scrollbars huge unnecessarily. Not every tab in the dialogue is currently able to fit in without scrolling on my laptop, but some of them are, and it's generally much nicer. Fixes #541
I did not make any changes to the settings themselves, everything …
=> Improve settings UI

addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitClassDoubler.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/doubler/CallableDoubler.gd, addons/gdUnit4/src/mocking/GdUnitMockFunctionDoubler.gd, addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd, addons/gdUnit4/src/spy/GdUnitSpyFunctionDoubler.gd, addons/gdUnit4/test/core/GdUnitClassDoublerTest.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/spy/ClassWithEnumConstructor.gd, addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd, addons/gdUnit4/test/spy/GdUnitSpyCallableTest.gd, addons/gdUnit4/test/spy/GdUnitSpyTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/544
- cleanup parser
- removed `extract_source_code`, it was only used in tests 
- add support to spy on `Callable`
- supports to spy on Callable on all functions exclusive `callv` and `call_deferred`
`call` and `call_deferred` are not possible to stub because of interface conflicts between `Callable` and `Object`
=> GD-544: Add Spy support for `Callable`

addons/gdUnit4/src/GdUnitFloatAssert.gd, addons/gdUnit4/src/GdUnitIntAssert.gd, addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFloatAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitIntAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitVectorAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitVariantAssertThatTest.gd, addons/gdUnit4/test/ui/parts/InspectorProgressBarTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/546
- do allow all Variant types for `is_equal` and `is_not_equal` when using the un-typed `assert_that`
- changed the fixed typed  `is_equal` and `is_not_equal` to accept Variant type
=> GD-546: Allow to test un-typed values by `assert_that`

addons/gdUnit4/test/GdUnitTestSuiteTest.gd
We miss the text coverage on `GdUnitTestSuite` for `get_child` and `get_node`
Added missing tests
=> GD-553: Add missing test coverage for `get_child` and `get_node`

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
Implements #559
https://github.com/user-attachments/assets/ed68cdd0-5873-4f08-b18f-9507487ccdba
Double clicking on a directory in the inspector does nothing currently, and causes an error.
IMO the expected behavior here should be to toggle collapse on the tree item.
- Fix 'no meta' error message when double clicking a directory
- Make double clicking a directory toggle its collapsed state
=> GD-559: add inspector directory collapse toggling

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml, README.md, addons/gdUnit4/src/monitor/ErrorLogEntry.gd, addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/test/asserts/GdUnitGodotErrorAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitGodotErrorWithAssertTest.gd, addons/gdUnit4/test/core/parse/GdFunctionDescriptorTest.gd, addons/gdUnit4/test/monitor/GodotGdErrorMonitorTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/569
- added Godot 4.4.dev2 to the CI
- fixes `GdFunctionDescriptorTest` to take new virtual functions into account
- fixes the `GodotGdErrorMonitor` for `push_error`, `push_warning` and script error scanning, the format has changed.
- update README.md
=> GD-569: Add Godot `4.4.dev2` to the CI workflows

addons/gdUnit4/src/report/template/css/styles.css
With the report footer's position CSS value set to `fixed`, the bottom test in a long list of tests is able to be viewed, but in Firefox the footer covers most of the bottom test.
Setting its position to `static` fixes this, and it looks correct in both Chrome and Firefox.
=> GD-590: Fix HTML test report footer overlapping in Firefox

addons/gdUnit4/src/core/GdArrayTools.gd, addons/gdUnit4/src/core/discovery/GdUnitTestDiscoverGuard.gd
see https://github.com/MikeSchulze/gdUnit4/issues/592 The discovery guard was not aware of parameterized test data has changed and missed notifying the test explorer to update.
- fix the test discover guard to respect test data indices changes on parameterized tests to finally update the listed tests in the test explorer.
=> GD-592: Fixed the detection of parameterized test data changes in `TestDiscoveryGuard` to notify the test explorer and update the structure.

addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/mocker/resources/ClassWithParameterGetterSetter.gd
see https://github.com/MikeSchulze/gdUnit4/issues/594
There was a bug in the script parser using hard coded check for getter/setter  parameter named `type`. Fixed by using a pattern to detect a getter/setter matching.
=> GD-594: Fix mock fails on class with parameter getter setter

.github/workflows/ci-pr.yml, addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/core/GdUnitSingleton.gd, addons/gdUnit4/src/core/execution/GdUnitExecutionContext.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseAfterStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestSuiteAfterStage.gd, addons/gdUnit4/src/core/thread/GdUnitThreadContext.gd, addons/gdUnit4/test/core/command/GdUnitCommandHandlerTest.gd
Running tests via CMD line shows a lot of memory leaks at program exit.
- fixed releasing of all singletons
- `func_assert` has problems with lambdas when using inside `timer.timeout.connect`, converted lambda into function
- Handling of stored asserts in the thread context results in inconsistency during cleanup
- fixed cleanup on `GdUnitCommandHandlerTest`
```
Statistics: | 947 tests cases | 0 error | 0 failed | 1 flaky | 13 skipped | 0 orphans |
Executed test suites: (100/104), 4 skipped
Executed test cases: (934/947), 13 skipped
Total time:        3min 0s 409ms
Open Report at: file:///home/runner/work/gdUnit4/gdUnit4/reports/report_1/index.html
Exit code: 0
----------------------------------------------------------------
Cleanup singletons ["GdUnitThreadManager", …
```
=> GD-598: Fixing memory leaks on test execution

addons/gdUnit4/src/core/templates/test_suite/GdUnitTestSuiteDefaultTemplate.gd, addons/gdUnit4/src/network/GdUnitTcpClient.gd, addons/gdUnit4/src/network/GdUnitTcpServer.gd
The default C# template still had `using GdUnit3`. It's easy to change the default template (thank you!) from project settings, but this should be a little nicer on everyone.
This changes the template to have `using GdUnit4`. This also changes error messages in `GdUnitTcp{Client,Server}.gd` to be attributed to `GdUnit4` instead of `GdUnit3`.
Some references still remain, left untouched here:
- One in FUNDING.yml, which appears to be an account name unlikely to have changed, and I wouldn't feel comfortable touching this one anyway.
- One each in bbcode_example.txt and markdown_example.txt. As these are examples taken from that era, I think these are fine to leave?
- gdUnit3-examples and all of its references. Given there are `res://` links to here, I'm not sure what migration would look …
=> Replace references to GdUnit3 with GdUnit4

addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/core/GdUnitSettings.gd, addons/gdUnit4/src/core/command/GdUnitCommandHandler.gd, addons/gdUnit4/src/core/discovery/GdUnitTestDiscoverer.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/core/command/GdUnitCommandHandlerTest.gd
The GdUnit4 Godot Editor plugin currently does not find any tests in the project root directory, even when configured to do so.
Fixes #607.
- Refactors external calls to `scan_test_directories` into a new `scan_all_test_directories` instead. These external calls all had the form `scan_test_directorys("res://", GdUnitSettings.test_root_folder(), [])`. This provides a cleaner API, and a logical place to add handling for the "include all resources" special case.
- When `scan_all_test_directories` is called to determine which resource paths should be included, and the project is configured to include all resources, it early returns `["res://"]`. Otherwise, it performs the current subfolder scanning logic via `scan_test_directories("res://", GdUnitSettings.test_root_folder(), [])`.
- Fixes a …
=> GD-607: Fix discovery of root test suites

addons/gdUnit4/plugin.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandler.gd, addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandlerV44.gdx, addons/gdUnit4/src/ui/menu/ScriptEditorContextMenuHandler.gd, addons/gdUnit4/src/ui/menu/ScriptEditorContextMenuHandlerV44.gdx
see https://github.com/MikeSchulze/gdUnit4/issues/616
- Removed the context menu creation form, the `GdUnitInspector` into the context menu classes.
- Provide different implementations for Godot 4.4 and lower to implement version specific solutions
- use for Godot4.4+ the new provided `EditorContextMenuPlugin` interfaces to add the context menus
- use for Godot4.3- the classic hacky way to add the context menus
- for script editor context menus we need to use the old way until https://github.com/godotengine/godot/pull/100556 is merged
=> GD-616: Use `EditorContextMenuPlugin` for Godot4.4.x

addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandlerV44.gdx
With https://github.com/MikeSchulze/gdUnit4/issues/616 introduced change has a little bug to evaluate the file type
use `gd` and `cs` for file type check (it was before script type check)
=> GD-616: fix file type check on filesystem context menu checks

addons/gdUnit4/src/core/command/GdUnitCommandHandler.gd, addons/gdUnit4/src/core/command/GdUnitShortcutAction.gd, addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandlerV44.gdx
We do a mistake on `EditorFileSystemContextMenuHandlerV44` by act on `gdunit_settings_changed` signal to add a new shortcut. Instead, we have to update the shortcut object to exchange the input event
- removed the invalid handling of settings, changed to update/add the shortcut
- fix on `CommandHandler` to update the input event for existing shortcuts
=> GD-616: Fix update shortcuts

addons/gdUnit4/src/GdUnitObjectAssert.gd, addons/gdUnit4/src/asserts/GdUnitObjectAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitObjectAssertImplTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/624
Added `is_inheriting` and `is_not_inheriting` to object assert and covered by tests
=> GD-624: Add `is_inheriting` and `is_not_inheriting` to object assert

addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/parse/GdScriptParsingFunctionDescriptors.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeBoolDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeFloatDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeIntDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeNodePathDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeRect2DefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeStringDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeStringNameDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeTransform2DDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeVector2DefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeVector2iDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeVector3DefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeVector3iDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeVector4DefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/basic_build_in_types/ClassWithBasicTypeVector4iDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/container_build_in_types/ClassWithArrayDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/container_build_in_types/ClassWithCallableDefaultArguments.gd, addons/gdUnit4/test/core/resources/parsing/functions/container_build_in_types/ClassWithDictionaryDefaultArguments.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd
The mock of an class containing a function with default dictionary argument was failing at runtime. The parse was not handling well the default argument parsing for dictionaries
- Fixed the script parser to handle dictionary as function arguments.
- Added more test coverage of parsing functions with default values.
- Added test with mocks a class containing a function with default dictionary argument
=> GD-629: Fix script parser to parse default dictionary function arguments

addons/gdUnit4/src/ui/GdUnitConsole.tscn
We want to copy a selected text from the gdunit console.
- Enable the selection
- Enable the context menu for copy
=> GD-631: Enable selection and context menu on the gdunit console

addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd, addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd, addons/gdUnit4/test/spy/resources/TestSceneWithProperties.tscn, addons/gdUnit4/test/spy/resources/test_scene_with_parmeters.gd
see https://github.com/MikeSchulze/gdUnit4/issues/645 
The spying scene loses the properties after assign the new spy script to the scene.
We copy all script properties from source to the spy after exchanging the script
=> GD-645: Spying on a scene with `@onready` properties loses the property values

.github/workflows/ci-dev.yml, .github/workflows/ci-pr.yml
We want to have clean tests and the test execution should always end with success. With the update to gdunit4-action/v1.1.5 warnings will not report as errors as default, we need to set the warnings-as-errors flag to true
add parameter `warnings-as-errors: true`
=> GD-653: Configure CI if test ends with warning to treat as error

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/core/command/GdUnitCommandHandler.gd, addons/gdUnit4/src/core/event/GdUnitEvent.gd, addons/gdUnit4/src/core/event/GdUnitEventInit.gd, addons/gdUnit4/src/ui/parts/InspectorProgressBar.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/GdUnitTestSuiteTest.gd
https://github.com/MikeSchulze/gdUnit4/issues/659
- emit `GdUnitInit` to reset the statistics before every new test run
- fix progress counter issues on flaky test execution
- fix UI glitches on counter representation in the tree
- remove unused counters from GdUnitEvent
=> GD-635:  Fix test run statistics counters

addons/gdUnit4/bin/GdUnitCmdTool.gd, addons/gdUnit4/src/core/event/GdUnitEvent.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestSuiteExecutionStage.gd, addons/gdUnit4/src/core/parse/GdUnitTestParameterSetResolver.gd, addons/gdUnit4/src/ui/GdUnitConsole.gd, addons/gdUnit4/src/ui/parts/InspectorStatusBar.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/GdUnitTestSuiteTest.gd, addons/gdUnit4/test/asserts/GdUnitGodotErrorWithAssertTest.gd, addons/gdUnit4/test/core/execution/GdUnitTestSuiteExecutorTest.gd
- removed obsolete TESTCASE_STATISTICS event
- fix test counter on the console
- fix counting based on TESTCASE_AFTER because we removed TESTCASE_STATISTICS
- fix initial progress counter
- fix skipped test reporting for parameterized tests
=> GD-635: Fix GdUnit console test counters

addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/attributes/TestCaseAttribute.gd, addons/gdUnit4/src/core/runners/GdUnitTestCIRunner.gd, addons/gdUnit4/src/core/runners/GdUnitTestResultReporter.gd, addons/gdUnit4/test/cmd/runtestDebug.tscn, addons/gdUnit4/test/core/GdUnitTestSuiteScannerTest.gd, addons/gdUnit4/test/core/parse/GdUnitTestParameterSetResolverTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/675
using the new `gdUnitTestResultReporter` to finally evaluate the exit status based on the tracked failure count
=> GD-635: Comand line tool returns 0 on failed tests

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/plugin.gd, addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandlerV44.gdx
Godot 4.4-rc1 is out, and we need to update the CI to run on the latest release candidate.
- update `godot-status` version from `dev7` to `rc1`
- improved the context_menu_script load check on plugin.gd
- fixed file system context menu collection now scripts instead of script paths
=> GD-678: Update CI to Godot 4.4-rc1

addons/gdUnit4/src/core/command/GdUnitCommandHandler.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/GdUnitInspector.tscn, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/683
- add test case record as metadata stored by key `gdunit_test_case`
- removed obsolete signals `run_testsuite` and `run_testcase`
- removed obsolete metadata attributes where is covered by new metadata `gdunit_test_case`
- collect test records from selected node and use command handler to execute
=> GD-635: Store the test case record on tree item and used as execute argument instead of `resource_path`

addons/gdUnit4/plugin.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/discovery/GdUnitTestDiscoverGuard.gd, addons/gdUnit4/src/core/event/GdUnitEvent.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseAfterStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseBeforeStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestSuiteExecutionStage.gd, addons/gdUnit4/src/core/runners/GdUnitTestCIRunner.gd, addons/gdUnit4/src/core/runners/GdUnitTestResultReporter.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/GdUnitTestResourceLoader.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd, addons/gdUnit4/test/core/event/GdUnitTestEventSerdeTest.gd, addons/gdUnit4/test/core/execution/GdUnitTestSuiteExecutorTest.gd, addons/gdUnit4/test/core/resources/testsuites/TestCaseFlaky.resource, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/688
- simplify `test_before` and `test_after`
- do find tree items by guid on explorer instead of using path + name
- use guid to find test record on discovery guard to build test output messages
- fix item creation by add test case record based on time type
- fix bug in `is_test_id` by using `equals` of `GdUnitGUID`
=> GD-653: Simplify GdUnitEvent by using the GdUnitGUID

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/661
- Reimplementation of the restructuring of the test tree based on the selected tree mode into a flat structure or a tree structure.
=> GD-635: Reimplement tree vs flat view

_advanced_testing/scene_runner/accessors.md
Up to date documentation for C# unit testing.
Added definition and example usage of `FindChild` function.
=> GD-695: Update documentation regarding find_child for C#

.editorconfig, addons/gdUnit4/src/dotnet/GdUnit4CSharpApi.cs, addons/gdUnit4/test/dotnet/ExampleTestSuite.cs, addons/gdUnit4/test/dotnet/GdUnit4CSharpApiTest.cs, gdUnit4.csproj
We want to update the .NET support to bind gdUnit4Net v4.4.0
- Update C# the project dependencies to gdUnit4Net v4.4.0
- add `.editorconfig` for standardizes coding styles and formatting
- Fix C# class warnings and do code formatting based on provided coding style
=> GD-635: Update .NET dependencies to gdUnit4Net v4.4.0 release candidate

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml
Since update the dorny/test-reporter to v2 the reports are no longer linked to the trigger CI PR
- Fix `ci-pr-publish-report.yml` by using parameter `use-actions-summary: 'false'`
- Simplify the reporter selection by evaluate the `matrix.godot-net` value
- Fix `cr-pr` .net test running on directory `res://addons/gdUnit4/test/dotnet`  (was changed from mono to dotner)
=> Update ci-pr-publish-report.yml to work with `dorny/test-reporter@v2`

addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/test/core/parse/GdFunctionDescriptorTest.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd
Mocking a class containing a function with typed arrays or dictionaries fails.
- Fix the parser to handle typed arrays and dictionaries
=> GD-714: Fix function argument parsing for typed arrays and typed dictionaries

addons/gdUnit4/runtest.cmd, addons/gdUnit4/runtest.sh
Users needed a way to override Godot binary path without changing environment variables. Godot .NET projects require C# code to be compiled before tests can run
- Add optional --godot_bin argument to specify Godot executable path
- Maintained fallback to GODOT_BIN environment variable if argument not provided
- Add version detection to automatically identify Godot .NET by checking for "mono"
- Run "dotnet build --debug" automatically when .NET is detected
- Added file existence and executable checks for better error handling
- Made both Windows and Unix runners consistent in behavior
=> GD-686: Add `--godot_bin` argument and Godot .NET detection to test-runners scripts

addons/gdUnit4/src/core/discovery/GdUnitTestCase.gd, addons/gdUnit4/src/core/runners/GdUnitTestCIRunner.gd, addons/gdUnit4/src/dotnet/GdUnit4CSharpApi.cs, addons/gdUnit4/src/dotnet/GdUnit4CSharpApiLoader.gd, addons/gdUnit4/test/dotnet/GdUnit4CSharpApiTest.cs, gdUnit4.csproj
We want to execute C# test inside the Godot GdUnit4 inspector.
- Delegate the C# test execution to `GdUnit4NetApiGodotBridge`
=> GD-635: Using `GdUnit4Net` test engine to execute C# tests

addons/gdUnit4/src/reporters/GdUnitTestReporter.gd, addons/gdUnit4/test/reporters/GdUnitConsoleTestReporterTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/724
- Use event `guid` to update the test statistics, (we address all tests by his unique id)
=> GD-635: Fix test case counting.

addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/src/doubler/GdFunctionDoubler.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/core/parse/GdScriptParsingFunctionDescriptors.gd, addons/gdUnit4/test/core/resources/parsing/functions/ClassWithVariantTypeDefaultArguments.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/mocker/resources/ClassWithVariantDefaultArguments.gd
When we try to mock a class containing functions with default argument typed Variant, the function doubling results into invalid function structure. The mocking fails with a parsing error.
- The doubler respects the Variant type and build the function signature inclusive type information
- Fix bug in value decoder to determine the original type of Variant value before decoding
- Fix function argument value set do not overwrite existing default value
- Add test coverage for default arguments of type Variant
=> GD-728: Fix mocking of functions with Variant dafaults

addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/core/resources/scenes/input_actions/InputEventTestScene.tscn, addons/gdUnit4/test/mocker/resources/scenes/TestScene.gd, addons/gdUnit4/test/mocker/resources/scenes/TestScene.tscn
The action strength is wrong set by the value of deadzone.
- Using event strength instead of deadzone
- Removed invalid uid's from the test scenes where resulting in loading warnings
=> GD-704 Fix action strength of `action_press` input handling

addons/gdUnit4/src/core/discovery/GdUnitTestCase.gd, addons/gdUnit4/src/core/execution/GdUnitTestSuiteExecutor.gd, addons/gdUnit4/src/core/parse/GdFunctionParameterSetResolver.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/core/GdUnitRunnerConfigTest.gd, addons/gdUnit4/test/core/discovery/GdUnitTestCaseTest.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscovererTest.gd, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd
Test discovery of inherit test suits results in wrong tree structure and execution paths.
- Store the original suite script resource path to build the fully_qualified_name, where is used in the inspector to build the tree.
- Fix test suite loading by use the new original base suite resource path
=> GD-664: Fix test discovery of inherit test suits results in invalid test tree structure

addons/gdUnit4/src/core/GdUnitRunnerConfig.gd, addons/gdUnit4/src/core/discovery/GdUnitTestDiscoverer.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/core/GdUnitRunnerConfigTest.gd, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd
On Godot start, the test inspector has initialed no test session data. When a user do press rerun tests, it will result into unresolvable guid's in the test inspector.
- Implementing a test session recovery mode to load previous test session and inject into the test inspector
- If the auto test discovery is enabled, sync fresh discovered tests with the previous test session guid's
=> GD-749: Fix `Internal Error: Can't find test id XXX-XXXX-XXXX-XXX`

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml, renovate.json
We want to update the CI workflows by renovate to the latest Godot prerelease version.
- Add renovate app to the repository
- Add renovate.json
=> Add Godot prerelease version to CI and enable renovate

addons/gdUnit4/plugin.cfg, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
When the `node_collapse` is set to true, the inspector tree disappears during test execution and reappear at the end of the run.
- Do not call `set_state_succeded` on tree root node. Collapse on  the root note will hide the complete tree because the root node it is not visible.
=> GD-756: Fix inspector tree disappears during test execution

addons/gdUnit4/src/core/discovery/GdUnitTestCase.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscovererTest.gd
The C# test discovery is broken since last release, it has introduced a new property `suite_resource_path` where is not present in C# test cases.
- Add fallback to `source_file` to set the `suite_resource_path` property
- Add missing test coverage for C# test discovery
=> GD-774: Fix broken C# test discovery

addons/gdUnit4/src/core/GdUnitProperty.gd, addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.gd
When installing GdUnit4 v5.0.x under Godot v4.3.x the console shows errors.
```
res://addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.gd:25 - Parse Error: Annotation "@warning_ignore_start" is not allowed in this level.
modules/gdscript/gdscript.cpp:2936 - Failed to load script "res://addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.gd" with error "Parse error". (User)
```
- Removed the `warning_ignore_start` and `warning_ignore_restore` where are not available in Godot 4.3.x
- Fixing compiler warnings in `GdUnitSettingsDialog`
=> GD-790: Fixing plugin loading problems under Godot v4.3.x

addons/gdUnit4/src/update/GdMarkDownReader.gd
When a user has a class named `Table`, it will result in conflicts with the GdMarkDownReader:Table class
- Rename the GdMarkDownReader:Table to avoid such conflicts
=> GD-794: GdMarkDownReader:Table class_name results in conflicts with user scripts

_advanced_testing/sceneRunner.md
Fix C# example that would cause compilation error when using `await` with `void` return type instead of `async Task`.
Changed method signature from `public void simulate_frame()` to `public async Task simulate_frame()`.
=> Fix C# async/await example in sceneRunner documentation

_advanced_testing/cmd.md
The command line tool on Linux is missing in the prerequisites that you need to set chmod +x for the shell file. The directory for the shell file is wrong documented. It says "gdunit4" instead of "gdUnit4"
- Fix the documentation by adding separate examples for Windows and Unix
- Fix the cmd tool path
=> DOC-818: Command line tool on linux is missing in the prerequisites

_testing/assert-array.md, _testing/assert-bool.md, _testing/assert-dictionary.md, _testing/assert-error.md, _testing/assert-file.md, _testing/assert-float.md, _testing/assert-function.md, _testing/assert-integer.md, _testing/assert-number.md, _testing/assert-object.md, _testing/assert-signal.md, _testing/assert-string.md, _testing/assert-that.md, _testing/assert-vector.md
The documentation has no details and examples
- add section for file assertions to the documentation
- show asserts ordered alphabetically
=> DOC-826: Missing documentation of `assertFile`

_testing/assert.md
There a no examples on the function documentation and users can be struggled to use it in the right way.
- Adding examples to show the usage.
=> DOC-842: Improve the documentaion for `append_error_message` and `override_error_message`

addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitDictionaryAssertImplTest.gd
When using `assert_dict` by validate two dictionaries are equal the failure report shows mixed/corrupted meta information.
- Removing the string diff building and show plain formatted metadata.
=> GD-858: Fix `assert_dict` shows corrupted failure message on `is_equal`

addons/gdUnit4/src/core/writers/GdUnitCSIMessageWriter.gd, addons/gdUnit4/src/reporters/console/GdUnitConsoleTestReporter.gd, addons/gdUnit4/test/core/writers/GdUnitCsiMessageWriterTest.gd
When writing a test and using `assert_str` to validate for an expected string the failure messages are different in the inspector and console.
- Removing the default richtext_normalize form the `GdUnitConsoleTestReporter`
- Adding bbcode to csi code converting in the `GdUnitCSIMessageWriter` to show colored reports on command line execution
```gd
func test_is_equal_example() -> void:
assert_str("This is an test Message").is_equal("This is a test message")
```
- gdUnit4 inspector 
- gdUnit4 console
- gdUnit4 cmd tool
=> GD-862: Fixes `assert_str` shows different failure report as in the inspector

_advanced_testing/scene_runner/actions.md, _advanced_testing/scene_runner/keys.md, _advanced_testing/scene_runner/mouse.md, _advanced_testing/scene_runner/sync_inputs.md, _advanced_testing/scene_runner/touchscreen.md
Example commands are wrong and need to be fixed for better developer experience.
Change `await_input_processed` to `runner.await_input_processed`.
See https://github.com/MikeSchulze/gdUnit4/issues/856 for full details
=> [DOC-856] Update  `await_input_processed` examples

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd, addons/gdUnit4/test/ui/parts/resources/gd_872/ATests.cs, addons/gdUnit4/test/ui/parts/resources/gd_872/AZTests.cs
When running C# tests, an internal error is shown, and the tree structure looks also invalid.
- Removed the internal item cache and resolve test suite items by search over all items by path and name.
- Adding test coverage to rebuild the original error scenario
=> GD-872: Fix Internal errors when running C# tests

addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/mocker/resources/scenes/TestScene.tscn
The `SimulateKey ` produces an `InputEventKey` without setting the Unicode value. This will result in possible issues on text input components that act on Unicode values.
- Set the missing `Unicode` on  `InputEventKey` creation
- Add test coverage to simulate a text input
=> GD-882: Fixing SceneRunner SimulateKey to provide missing Unicode

addons/gdUnit4/src/core/GdUnitSignalCollector.gd, addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd
If a user wants to test whether a signal is emitted and then check that it is not emitted again, this will fail if the Any matcher is used as the signal parameter.
- Add missing test coverage
- We delete the matching received signal argument using `GdObjects.equals`. Using array `erase` uses object reference equality, which does not work for argument matchers.
=> GD-878: Fixes verify a signal is NOT emitted twice by using argument matchers

addons/gdUnit4/src/GdUnitArrayAssert.gd, addons/gdUnit4/src/GdUnitAssert.gd, addons/gdUnit4/src/GdUnitBoolAssert.gd, addons/gdUnit4/src/GdUnitDictionaryAssert.gd, addons/gdUnit4/src/GdUnitFailureAssert.gd, addons/gdUnit4/src/GdUnitFileAssert.gd, addons/gdUnit4/src/GdUnitFloatAssert.gd, addons/gdUnit4/src/GdUnitFuncAssert.gd, addons/gdUnit4/src/GdUnitGodotErrorAssert.gd, addons/gdUnit4/src/GdUnitIntAssert.gd, addons/gdUnit4/src/GdUnitObjectAssert.gd, addons/gdUnit4/src/GdUnitResultAssert.gd, addons/gdUnit4/src/GdUnitSignalAssert.gd, addons/gdUnit4/src/GdUnitStringAssert.gd, addons/gdUnit4/src/GdUnitVectorAssert.gd, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFileAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFloatAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitGodotErrorAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitIntAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitResultAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitStringAssertImpl.gd
The GdUnit4 assertion API faked interfaces to represent a small class with class documentation without overloaded implementation code. With Godot 4.5, GDScript now supports abstract classes and functions, so we should switch to that.
- Convert `is_equal` to abstract and add missing implementation
=> GD-905: Convert base assert function is_equal to abstract (part3)

addons/gdUnit4/src/GdUnitArrayAssert.gd, addons/gdUnit4/src/GdUnitAssert.gd, addons/gdUnit4/src/GdUnitBoolAssert.gd, addons/gdUnit4/src/GdUnitDictionaryAssert.gd, addons/gdUnit4/src/GdUnitFailureAssert.gd, addons/gdUnit4/src/GdUnitFileAssert.gd, addons/gdUnit4/src/GdUnitFloatAssert.gd, addons/gdUnit4/src/GdUnitFuncAssert.gd, addons/gdUnit4/src/GdUnitGodotErrorAssert.gd, addons/gdUnit4/src/GdUnitIntAssert.gd, addons/gdUnit4/src/GdUnitObjectAssert.gd, addons/gdUnit4/src/GdUnitResultAssert.gd, addons/gdUnit4/src/GdUnitSignalAssert.gd, addons/gdUnit4/src/GdUnitStringAssert.gd, addons/gdUnit4/src/GdUnitVectorAssert.gd, addons/gdUnit4/src/asserts/GdUnitAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitBoolAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFailureAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFileAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFloatAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitFuncAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitGodotErrorAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitIntAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitResultAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitSignalAssertImpl.gd, addons/gdUnit4/src/asserts/GdUnitStringAssertImpl.gd
The GdUnit4 assertion API faked interfaces to represent a small class with class documentation without overloaded implementation code. With Godot 4.5, GDScript now supports abstract classes and functions, so we should switch to that.
- Convert `append_failure_message` to abstract and add missing implementation
=> GD-905: Convert base assert function append_failure_message to abstract (part6)

addons/gdUnit4/src/GdUnitArrayAssert.gd, addons/gdUnit4/src/GdUnitBoolAssert.gd, addons/gdUnit4/src/GdUnitDictionaryAssert.gd, addons/gdUnit4/src/GdUnitFailureAssert.gd, addons/gdUnit4/src/GdUnitFileAssert.gd, addons/gdUnit4/src/GdUnitFloatAssert.gd, addons/gdUnit4/src/GdUnitFuncAssert.gd, addons/gdUnit4/src/GdUnitGodotErrorAssert.gd, addons/gdUnit4/src/GdUnitIntAssert.gd, addons/gdUnit4/src/GdUnitObjectAssert.gd, addons/gdUnit4/src/GdUnitResultAssert.gd, addons/gdUnit4/src/GdUnitSignalAssert.gd, addons/gdUnit4/src/GdUnitStringAssert.gd, addons/gdUnit4/src/GdUnitVectorAssert.gd
The GdUnit4 assertion API faked interfaces to represent a small class with class documentation without overloaded implementation code. With Godot 4.5, GDScript now supports abstract classes and functions, so we should switch to that.
- Convert functions to abstract
=> GD-905: Convert base assert function to abstract (part7)

.github/workflows/gdlint.yml, addons/gdUnit4/src/GdUnitArrayAssert.gd, addons/gdUnit4/src/asserts/GdUnitArrayAssertImpl.gd, addons/gdUnit4/src/core/GdArrayTools.gd, addons/gdUnit4/test/asserts/GdUnitArrayAssertImplTest.gd
Before, Godot 4.5 has no support for variadic function arguments, and we have to use arrays as arguments to define the expected values.
- Extend the `assert_array` to allow variadic function arguments
- temporary disable until https://github.com/Scony/godot-gdscript-toolkit/issues/399 is fixed
=> GD-903: Add support for variadic argument to assert_array

addons/gdUnit4/src/GdUnitDictionaryAssert.gd, addons/gdUnit4/src/asserts/GdUnitDictionaryAssertImpl.gd, addons/gdUnit4/test/asserts/GdUnitDictionaryAssertImplTest.gd
Before, Godot 4.5 has no support for variadic function arguments, and we have to use arrays as arguments to define the expected values.
- Extend the `assert_dict` to allow variadic function arguments
=> GD-904: Add variadic argument support to `assert_dict`

addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestSuiteAfterStage.gd, addons/gdUnit4/src/core/runners/GdUnitTestRunner.gd, addons/gdUnit4/src/core/runners/GdUnitTestRunner.tscn, addons/gdUnit4/src/core/runners/GdUnitTestSessionRunner.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd
Calling runner.move_window_to_foreground() does not raise the testing window to the foreground.
- Fixing move_window_to_foreground 
- Do set the correct window mode dependent to the embedded window mode
- Adding Linux specific test fix because of [Godot issue](https://github.com/godotengine/godot/issues/111119)
=> GD-914,GD-893: Fix move_window_to_foreground

addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/core/GdDiffTool.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/network/GdUnitTcpNode.gd, addons/gdUnit4/test/asserts/GdUnitSignalAssertImplTest.gd, addons/gdUnit4/test/asserts/GdUnitStringAssertImplTest.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscoverGuardTest.gd, addons/gdUnit4/test/core/discovery/GdUnitTestDiscovererTest.gd, addons/gdUnit4/test/core/discovery/resources/DiscoverExampleTestSuite.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/core/runners/GdUnitTestCIRunnerTest.gd
The discovery of tests was failing when the name contains Unicode characters. The string comparison had also issues to compare strings containing Unicode.
- Fixing the script parser to support Unicode characters as variables and names
- Fixing the netcode to transport Unicode characters by using utf16 encoding
- Fixing string comparison by using utf32 encoding to support Unicode characters
- Significant performance improvement of string diff building
=> GD-909: Add support for unicode characters
