addons/gdUnit4/src/ui/GdUnitToolsDialog.gd, addons/gdUnit4/src/ui/GdUnitToolsDialog.tscn, addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd, addons/gdUnit4/src/ui/templates/TestSuiteTemplate.tscn
- fix the dialog and components according to the Godot4 UI API changes
=> GD-17: Fix broken GdUnitSettings dialog

addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/core/GdUnitExecutor.gd, addons/gdUnit4/src/core/GdUnitMemoryPool.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/mocking/GdUnitMockBuilder.gd, addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd, addons/gdUnit4/test/core/GdUnitMemoryPoolTest.gd, addons/gdUnit4/test/core/GdUnitToolsTest.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/spy/GdUnitSpyTest.gd, project.godot
- GdUnitMemoryPool
- extending now from RefCounted
- cleanup and centralize memory pool code in this class
- format code
=> Cleanup `GdUnitMemoryPool`

addons/gdUnit4/plugin.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/update/GdUnitUpdate.gd, addons/gdUnit4/src/update/GdUnitUpdate.tscn, addons/gdUnit4/src/update/GdUnitUpdateNotify.gd, addons/gdUnit4/src/update/GdUnitUpdateNotify.tscn
- split update logic into two parts
- first show release and download update
- second as a temporay resource to process the finally update
=> GD-45:  Rework on GdUnit update logic

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd
Stoping a runing parameterized tests was not stop the spinning icon on a running test
Fixed status update in the tree inspector and simplify code
=> GD-71: Stop inspector spinner when testcase is manually stopped

_advanced_testing/argument_matchers.md, _advanced_testing/fuzzing.md, _advanced_testing/index.md, _advanced_testing/mock.md, _advanced_testing/paramerized_tests.md, _advanced_testing/sceneRunner.md, _advanced_testing/spy.md, _faq/test-case.md
With GdUnit4 we need to update the documentation.
Initial update of the documentation with reference to GdUnit4
=> GD-147: Update documentation pages to GdUnit4 part 5

addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit4/test/mocker/resources/scenes/TestScene.gd
Fixes #198 and #200
Closes PRs #199 and #201
=> Add `set_property` and fix `get_property` on SceneRunner

CONTRIBUTING.md
The documentation was not up to date and lacked important information for providing pull requests
Updated the documentation and added missing parts.
=> GD-204: Update contributing documentation

README.md
We missed the contribution cuidelines in the README.MD
Add new section contribution cuidelines.
=> GD-210: Add contribution cuidelines to README

_advanced_testing/sceneRunner.md, _asserts/assert-error.md, _asserts/index.md, _faq/C#.md, _faq/ci.md, _faq/run-tests.md, _faq/skip-tests.md, _faq/test-case.md, _faq/test-suite.md, index.md
- document `set_property` on SceneRunner
- document `assert_error`
- document how to skip tests
=> GD-231: Update documentation to v4.1.4

_faq/ci.md
The actual example was to complicated and needs to replaced by a simple one
=> GD-262: Update documentaion with better ci workflow example

addons/gdUnit4/bin/GdUnitCopyLog.gd, addons/gdUnit4/src/asserts/GdAssertMessages.gd, addons/gdUnit4/src/asserts/GdUnitResultAssertImpl.gd, addons/gdUnit4/src/cmd/CmdArgumentParser.gd, addons/gdUnit4/src/cmd/CmdCommandHandler.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnitResult.gd, addons/gdUnit4/src/core/GdUnitRunnerConfig.gd, addons/gdUnit4/src/core/GdUnitTestSuiteBuilder.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/mono/GdUnit4MonoApiLoader.gd, addons/gdUnit4/src/network/GdUnitTask.gd, addons/gdUnit4/src/network/GdUnitTcpClient.gd, addons/gdUnit4/src/network/GdUnitTcpServer.gd, addons/gdUnit4/test/GdUnitTestSuiteTest.gd, addons/gdUnit4/test/asserts/GdUnitResultAssertImplTest.gd, addons/gdUnit4/test/core/GdObjectsTest.gd, addons/gdUnit4/test/core/GdUnitResultTest.gd
-  to avoid name conflicts with other add-ons
just renamed
=> GD-283: Rename `Result` into `GdUnitResult`

Gemfile, Gemfile.lock, _advanced_testing/argument_matchers.md, _advanced_testing/fuzzing.md, _advanced_testing/mock.md, _advanced_testing/sceneRunner.md, _advanced_testing/spy.md, _asserts/assert-string.md, _config.yml, _faq/ci.md, _layouts/default.html, about.md, index.md
Documentation update to v4.2.1
- assert_str() now accepts StringNames
- argument matchers can now be used everywhere
- scene runner has improved `simulate_mouse_move_relative`
- scene runner has added `simulate_mouse_move_absolute`
- update Continuous Integration Testing documentation to using gdunit4-action
=> GD-318: Update documentation to v4.2.1

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml
=> Try to fix workflow to publish test reports

addons/gdUnit4/src/Fuzzers.gd, addons/gdUnit4/src/GdUnitBoolAssert.gd, addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/src/core/GdUnitSignalAwaiter.gd, addons/gdUnit4/src/core/GodotVersionFixures.gd, addons/gdUnit4/src/fuzzers/FloatFuzzer.gd, addons/gdUnit4/src/fuzzers/IntFuzzer.gd, addons/gdUnit4/src/fuzzers/StringFuzzer.gd, addons/gdUnit4/src/fuzzers/Vector2Fuzzer.gd, addons/gdUnit4/src/fuzzers/Vector3Fuzzer.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd, addons/gdUnit4/test/core/GdUnitSignalAwaiterTest.gd
see #427
Fix
- fuzzers
- GdUnitSceneRunner
- GdUnitSignalAwaiter
=> GD-427: Do use typed variables and arguments (part3)

addons/gdUnit4/src/core/GdFunctionDoubler.gd, addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/GdUnit4Version.gd, addons/gdUnit4/src/core/GdUnitClassDoubler.gd, addons/gdUnit4/src/core/GdUnitObjectInteractions.gd, addons/gdUnit4/src/core/GdUnitRunner.gd, addons/gdUnit4/src/core/GdUnitSettings.gd, addons/gdUnit4/src/core/GdUnitTestSuiteScanner.gd, addons/gdUnit4/src/core/GdUnitTools.gd, addons/gdUnit4/src/core/LocalTime.gd, addons/gdUnit4/src/core/_TestCase.gd, addons/gdUnit4/src/core/parse/GdClassDescriptor.gd, addons/gdUnit4/src/mocking/GdUnitMockFunctionDoubler.gd, addons/gdUnit4/src/spy/GdUnitSpyFunctionDoubler.gd, addons/gdUnit4/test/core/GdObjectsTest.gd, addons/gdUnit4/test/core/GdUnit4VersionTest.gd, addons/gdUnit4/test/core/GdUnitObjectInteractionsTemplateTest.gd, addons/gdUnit4/test/core/GdUnitResultTest.gd, addons/gdUnit4/test/core/GdUnitRunnerConfigTest.gd, addons/gdUnit4/test/core/GdUnitSettingsTest.gd, addons/gdUnit4/test/core/GdUnitSingletonTest.gd, addons/gdUnit4/test/core/GdUnitToolsTest.gd, addons/gdUnit4/test/core/LocalTimeTest.gd, addons/gdUnit4/test/core/resources/Area4D.txt, addons/gdUnit4/test/core/resources/AtmosphereData.txt, addons/gdUnit4/test/mocker/GodotClassNameFuzzer.gd, addons/gdUnit4/test/mocker/resources/AdvancedTestClass.gd
=> GD-427: Do use typed variables and arguments (part4)

addons/gdUnit4/src/core/GdObjects.gd, addons/gdUnit4/src/core/parse/GdClassDescriptor.gd, addons/gdUnit4/src/core/parse/GdDefaultValueDecoder.gd, addons/gdUnit4/src/core/parse/GdFunctionArgument.gd, addons/gdUnit4/src/core/parse/GdFunctionDescriptor.gd, addons/gdUnit4/src/core/parse/GdScriptParser.gd, addons/gdUnit4/src/core/parse/GdUnitTestParameterSetResolver.gd, addons/gdUnit4/test/GdUnitTestResourceLoader.gd, addons/gdUnit4/test/core/parse/GdDefaultValueDecoderTest.gd, addons/gdUnit4/test/core/parse/GdFunctionDescriptorTest.gd, addons/gdUnit4/test/core/parse/GdScriptParserTest.gd, addons/gdUnit4/test/core/parse/GdUnitExpressionRunnerTest.gd, addons/gdUnit4/test/core/parse/GdUnitTestParameterSetResolverTest.gd
=> GD-427: Do use typed variables and arguments (part5)

addons/gdUnit4/src/core/command/GdUnitCommand.gd, addons/gdUnit4/src/core/command/GdUnitCommandHandler.gd, addons/gdUnit4/src/core/command/GdUnitShortcutAction.gd, addons/gdUnit4/src/core/thread/GdUnitThreadContext.gd, addons/gdUnit4/src/core/thread/GdUnitThreadManager.gd, addons/gdUnit4/src/extractors/GdUnitFuncValueExtractor.gd, addons/gdUnit4/src/matchers/AnyArgumentMatcher.gd, addons/gdUnit4/src/matchers/AnyBuildInTypeArgumentMatcher.gd, addons/gdUnit4/src/matchers/ChainedArgumentMatcher.gd, addons/gdUnit4/src/matchers/EqualsArgumentMatcher.gd, addons/gdUnit4/src/matchers/GdUnitArgumentMatchers.gd, addons/gdUnit4/src/ui/ScriptEditorControls.gd, addons/gdUnit4/src/ui/menu/ScriptEditorContextMenuHandler.gd, addons/gdUnit4/test/core/command/GdUnitCommandHandlerTest.gd, addons/gdUnit4/test/core/event/GdUnitTestEventSerdeTest.gd, addons/gdUnit4/test/extractors/GdUnitFuncValueExtractorTest.gd, addons/gdUnit4/test/matchers/AnyArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/AnyClazzArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/ChainedArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/CustomArgumentMatcherTest.gd, addons/gdUnit4/test/matchers/GdUnitArgumentMatchersTest.gd, addons/gdUnit4/test/matchers/resources/CustomArgumentMatcherTestClass.gd
see #427
matchers and commands
=> GD-427: Do use typed variables and arguments (part6)

addons/gdUnit4/src/GdUnitTestSuite.gd, addons/gdUnit4/src/core/execution/GdUnitMemoryObserver.gd, addons/gdUnit4/src/mocking/GdUnitMockBuilder.gd, addons/gdUnit4/src/spy/GdUnitSpyBuilder.gd, addons/gdUnit4/test/core/resources/sources/test_person.gd, addons/gdUnit4/test/mocker/GdUnitMockBuilderTest.gd, addons/gdUnit4/test/mocker/GdUnitMockerTest.gd, addons/gdUnit4/test/mocker/resources/ClassWithDefaultBuildIntTypes.gd, addons/gdUnit4/test/mocker/resources/ClassWithPoolStringArrayFunc.gd, addons/gdUnit4/test/mocker/resources/TestPersion.gd, addons/gdUnit4/test/spy/ClassWithEnumConstructor.gd, addons/gdUnit4/test/spy/GdUnitSpyBuilderTest.gd, addons/gdUnit4/test/spy/GdUnitSpyTest.gd
=> GD-427: Do use typed variables and arguments (part7)

addons/gdUnit4/src/core/execution/GdUnitExecutionContext.gd, addons/gdUnit4/src/core/execution/GdUnitTestReportCollector.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseAfterStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseBeforeStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestCaseExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestSuiteExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/fuzzed/GdUnitTestCaseFuzzedExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/parameterized/GdUnitTestCaseParameterizedExecutionStage.gd, addons/gdUnit4/src/core/execution/stages/parameterized/GdUnitTestCaseParameterizedTestStage.gd, addons/gdUnit4/src/core/execution/stages/single/GdUnitTestCaseSingleExecutionStage.gd, addons/gdUnit4/src/monitor/ErrorLogEntry.gd, addons/gdUnit4/src/monitor/GdUnitMonitor.gd, addons/gdUnit4/src/monitor/GdUnitOrphanNodesMonitor.gd, addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/test/core/execution/GdUnitExecutionContextTest.gd, addons/gdUnit4/test/core/execution/GdUnitTestSuiteExecutorTest.gd
=> GD-427: Do use typed variables and arguments (part8)

addons/gdUnit4/src/network/rpc/dtos/GdUnitTestSuiteDto.gd, addons/gdUnit4/src/report/GdUnitByPathReport.gd, addons/gdUnit4/src/ui/EditorFileSystemControls.gd, addons/gdUnit4/src/ui/GdUnitConsole.gd, addons/gdUnit4/src/ui/GdUnitInspector.gd, addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandler.gd, addons/gdUnit4/src/ui/menu/GdUnitContextMenuItem.gd, addons/gdUnit4/src/ui/parts/InspectorMonitor.gd, addons/gdUnit4/src/ui/parts/InspectorProgressBar.gd, addons/gdUnit4/src/ui/parts/InspectorStatusBar.gd, addons/gdUnit4/src/ui/parts/InspectorToolBar.gd, addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/src/ui/settings/GdUnitInputCapture.gd, addons/gdUnit4/src/ui/settings/GdUnitSettingsDialog.gd, addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd
=> GD-427: Do use typed variables and arguments (part10)

assets/css/site-header.css
Enable the sidebar to be responsive to support mobile users.
Simplified CSS while still keeping the logo large.
=> GD-457: Fix CSS so that sidebar is responsive on small screens.

addons/gdUnit4/src/monitor/GodotGdErrorMonitor.gd, addons/gdUnit4/test/monitor/GodotGdErrorMonitorTest.gd
see https://github.com/MikeSchulze/gdUnit4/issues/474
Do cleanup log entries after collected as reports
=> GD-474: Fix test Godot Runtime Error is reported repeatedly

.github/ISSUE_TEMPLATE/bug_report.yml, addons/gdUnit4/plugin.cfg
=> bump to v4.3.1

_advanced_testing/signals.md, _csharp_project_setup/vstest-adapter.md
- add debugger info for Rider 2024.2
- add missing monitor signal documentation for C# API
=> Update documentation to v4.3.0

addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd
- improve inline documentation
- fix formatting/code styles
=> Update `SceneRunner` inline documentation and fix formatting issues

addons/gdUnit4/src/GdUnitSceneRunner.gd, addons/gdUnit4/src/core/GdUnitSceneRunnerImpl.gd, addons/gdUnit4/src/core/execution/stages/GdUnitTestSuiteAfterStage.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerInputEventTest.gd, addons/gdUnit4/test/core/GdUnitSceneRunnerTest.gd
- improve inline documentation
- fix formatting/code styles
=> Update SceneRunner documentation and fix formatting issues

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/src/ui/menu/EditorFileSystemContextMenuHandler.gd, addons/gdUnit4/test/core/GdArrayToolsTest.gd, addons/gdUnit4/test/core/parse/GdDefaultValueDecoderTest.gd, project.godot
a new dev version is out and we need to run against to ensure nothing is broken
=> Update ci-pr to dev6

.github/workflows/ci-pr-publish-report.yml, .github/workflows/ci-pr.yml, addons/gdUnit4/test/mocker/GodotClassNameFuzzer.gd
update ci-pr workflow to Godot4.4-dev7 release
=> Update`Godot4.4-dev7` on ci-pr workflow

addons/gdUnit4/src/core/discovery/GdUnitGUID.gd, addons/gdUnit4/src/core/discovery/GdUnitTestCase.gd, addons/gdUnit4/test/core/discovery/GdUnitGuidTest.gd
https://github.com/MikeSchulze/gdUnit4/issues/636
created `GdUnitGUID` + `GdUnitTestCase`
=> GD-635: Introduce new test case record

.github/actions/workflow-cleanup/index.js, .github/workflows/workflow-cleanup.yml, .idea/.idea.gdUnit4/.idea/codeStyles/Project.xml, .idea/.idea.gdUnit4/.idea/codeStyles/codeStyleConfig.xml
The workflow is a kind of outdated and needs to be revisited.
improved the workflow by adding input parameters and improve log messages
=> Revisit `workflow-cleanup`

.github/workflows/ci-pr.yml, addons/gdUnit4/src/core/GdUnitSignalAwaiter.gd
- add all 4.4 versions to ci to find last working version
=> GD-701: Fix signal 11 crash on Ubuntu

addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd, addons/gdUnit4/test/ui/parts/InspectorTreeMainPanelTest.gd
The sorting was not correct working and needs to be fixed.
- Rewrite the sorting by folders should be always on top and if sorting unsorted should show the original order
- Better test coverage for the sorting modes
=> GD-732: Fix test inspector sorting modes

addons/gdUnit4/plugin.cfg
=> Bump to V5.0.2

addons/gdUnit4/src/update/GdUnitUpdate.gd
When using the GdUnit4 upgrade tooling, it should recompile a C# project after successfully installed the new version. This is necessary to avoid loading outdated GdUnit4CSharpApi
Adding a rebuild step to the update tool
=> GD-857: Run rebuild c# project on update to new GdUnit4 version
